---

    # 
  # 
  # ======== Result =========
  # 
  # best option name IVF8192,PQ16
  # nprobe: 22
  # QPS 8576.329331046312
  # stage_option_list
  # Stage 2:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 1.0
  #         URAM: 144.0
  #         FF: 103664
  #         LUT: 80688
  #         DSP48E: 522
  #         
  # QPS: 9522.513943681131
  # Cycles per query: 14702
  # STAGE2_ON_CHIP: True
  # STAGE2_OFF_CHIP_START_CHANNEL:None
  # PE_NUM_CENTER_DIST_COMP: 9
  # Stage 3:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 6.0
  #         URAM: 0
  #         FF: 13510.619999999999
  #         LUT: 14546.340000000002
  #         DSP48E: 0
  #         
  # QPS: 17023.346303501945
  # Cycles per query: 8224
  # STAGE_3_PRIORITY_QUEUE_LEVEL: 2
  # STAGE_3_PRIORITY_QUEUE_L1_NUM: 2
  # Stage 4:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 296.0
  #         URAM: 192
  #         FF: 77848
  #         LUT: 60104
  #         DSP48E: 432
  #         
  # QPS: 10835.913312693498
  # Cycles per query: 12920
  # PE_NUM_TABLE_CONSTRUCTION: 8
  # Stage 5:
  # 
  #         HBM_bank: 12.0
  #         BRAM_18K: 756.0
  #         URAM: 0.0
  #         FF: 211716.0
  #         LUT: 196968.0
  #         DSP48E: 1080.0
  #         
  # QPS: 8576.329331046312
  # Cycles per query: 16324
  # HBM_CHANNEL_NUM: 12
  # STAGE5_COMP_PE_NUM: 36
  # Stage 6:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 146.0
  #         URAM: 0
  #         FF: 157001.09999999998
  #         LUT: 165191.7
  #         DSP48E: 0
  #         
  # QPS: 16447.36842105263
  # Cycles per query: 8512
  # 
  # SORT_GROUP_ENABLE: False
  # SORT_GROUP_NUM: None
  # STAGE_6_PRIORITY_QUEUE_LEVEL: 2
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: None
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: None
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: None
  #         
  # total_valid_design: 267985
  # Total resource consumption: (with shell)
  # 
  #         HBM_bank: 12.0
  #         BRAM_18K: 1645.0
  #         URAM: 336.0
  #         FF: 887883.72
  #         LUT: 711259.04
  #         DSP48E: 2038.0
  #         
  # Total resource consumption: (accelerator kernel without shell)
  # 
  #         HBM_bank: 12.0
  #         BRAM_18K: 1205.0
  #         URAM: 336.0
  #         FF: 563739.72
  #         LUT: 517498.04
  #         DSP48E: 2034.0
  #         
  # Per Stage Utilization rate (Total = FPGA):
  # 
  # Stage 2: {'BRAM_18K': '0.0248015873015873%', 'DSP48E': '5.784574468085106%', 'FF': '3.9758222876779574%', 'LUT': '6.189248895434463%', 'URAM': '15.0%'}
  # Stage 3: {'BRAM_18K': '0.1488095238095238%', 'DSP48E': '0.0%', 'FF': '0.5181724042709868%', 'LUT': '1.1157906848306334%', 'URAM': '0.0%'}
  # Stage 4: {'BRAM_18K': '7.341269841269842%', 'DSP48E': '4.787234042553192%', 'FF': '2.9857020127638685%', 'LUT': '4.6103338242513505%', 'URAM': '20.0%'}
  # Stage 5: {'BRAM_18K': '18.75%', 'DSP48E': '11.96808510638298%', 'FF': '8.119937407952872%', 'LUT': '15.10861561119293%', 'URAM': '0.0%'}
  # Stage 6: {'BRAM_18K': '3.6210317460317465%', 'DSP48E': '0.0%', 'FF': '6.021458486745212%', 'LUT': '12.67118464653903%', 'URAM': '0.0%'}
  # Per Stage Utilization rate (Total = Accelerator Kernel (without shell)):
  # 
  # Stage 2: {'BRAM_18K': '0.08298755186721991%', 'DSP48E': '25.663716814159294%', 'FF': '18.38862800017001%', 'LUT': '15.591943111514006%', 'URAM': '42.857142857142854%'}
  # LUT only:
  # Stage 2: 15.591943111514006%
  # Stage 3: {'BRAM_18K': '0.49792531120331945%', 'DSP48E': '0.0%', 'FF': '2.396606008176965%', 'LUT': '2.8108976026266697%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 3: 2.8108976026266697%
  # Stage 4: {'BRAM_18K': '24.564315352697093%', 'DSP48E': '21.238938053097346%', 'FF': '13.809209682794748%', 'LUT': '11.614343505532892%', 'URAM': '57.14285714285714%'}
  # LUT only:
  # Stage 4: 11.614343505532892%
  # Stage 5: {'BRAM_18K': '62.738589211618255%', 'DSP48E': '53.09734513274337%', 'FF': '37.5556293957786%', 'LUT': '38.06159343134904%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 5: 38.06159343134904%
  # Stage 6: {'BRAM_18K': '12.116182572614107%', 'DSP48E': '0.0%', 'FF': '27.84992691307967%', 'LUT': '31.921222348977402%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 6: 31.921222348977402%
  # Total Utilization rate:
  # {'BRAM_18K': '40.79861111111111%', 'DSP48E': '22.58421985815603%', 'FF': '34.05297772459499%', 'LUT': '54.55779332351498%', 'URAM': '35.0%'}


  # Constants
  NLIST: 8192
  NPROBE: 22
  D: 128
  M: 16
  K: 256
  TOPK: 10

  QUERY_NUM: 10000

  LARGE_NUM: 99999999 # used to init the heap
  # stage 1
  OPQ_ENABLE: False
  OPQ_UNROLL_FACTOR: <--OPQ_unroll_factor--> # 4 or 8, the larger the better performance, left None if OPQ_ENABLE=False, only used when OPQ_ENABLE=True

  # stage 2
  # except last PE: compute more distances per query, last one compute less
  # e.g., nlist = 8192, PE num = 15, 
  #   each of the first 14 PEs construct 547 tables (8192 / 15 round up), 
  #   while the last constructs 534: 14 * 547 + 534 = 8192
  STAGE2_ON_CHIP: True
  PE_NUM_CENTER_DIST_COMP: 9

  # stage 3
  STAGE_3_PRIORITY_QUEUE_LEVEL: 2 # support 1 or 2
  STAGE_3_PRIORITY_QUEUE_L1_NUM: 2 # only used when STAGE_3_PRIORITY_QUEUE_LEVEL=2

  # stage 4
  # except last PE: construct more tables per query, last one construct less
  # e.g., nprobe = 17, PE num = 6, each of the first 5 PEs construct 3 tables, 
  #   while the last constructs 2: 5 * 3 + 2 = 17
  PE_NUM_TABLE_CONSTRUCTION: 8

  # stage 5
  # (HBM_CHANNEL_NUM * 3 / STAGE5_COMP_PE_NUM) must be integar
  # e.g., default 1 HBM channel -> 3 PQ code streams -> STAGE5_COMP_PE_NUM = 3 * HBM_CHANNEL_NUM
  # e.g., merge content of 1 HBM channel to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM
  # e.g., merge content of 2 HBM channels to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM / 2
  HBM_CHANNEL_NUM: 12 # PQ code stream num = 3 * HBM_CHANNEL_NUM
  STAGE5_COMP_PE_NUM: 36

  # stage 6
  # there could be a sorting network before the priority queue group (SORT_GROUP_ENABLE)
  #   if not, set SORT_GROUP_ENABLE to False, and SORT_GROUP_NUM to 0 or None
  # number of 16 outputs per cycle, e.g., HBM channel num = 10, comp PE num = 30, then 
  #   SORT_GROUP_NUM = 2; if HBM channel = 12, PE_num = 36, then SORT_GROUP_NUM = 3
  SORT_GROUP_ENABLE: False
  SORT_GROUP_NUM: 0 # only used when SORT_GROUP_ENABLE=True
  STAGE_6_PRIORITY_QUEUE_LEVEL: 2 # supported level num: 2 or 3
  # only fill STAGE_6_PRIORITY_QUEUE_L2_NUM, STAGE_6_STREAM_PER_L2_QUEUE_LARGER, STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  #   when STAGE_6_PRIORITY_QUEUE_LEVEL = 3, else left them blank
  # Must subject to: L1 stream num = (without sort-reduction unit) STAGE5_COMP_PE_NUM * 2 
  #                  or = (with sort reduction) 16 * 2
  # (STAGE_6_PRIORITY_QUEUE_L2_NUM - 1) * STAGE_6_STREAM_PER_L2_QUEUE_LARGER + STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: 2 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: 6 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: 4 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3

  # Dataset config
  DB_SCALE: 100M # 1M to 1000M
  FPGA_NUM: 1 # e.g., can use 8 FPGAs to serve 1000M dataset, each stores 125M vectors

  # Data directory (don't add "/" after the dir)
  #   e.g., dir=/home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks, 
  #     then the content for HBM0 is:
  #     /home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks/HBM_bank_0_raw
  # DATA_DIR: "/mnt/scratch/wenqi/saved_npy_data/FPGA_data_SIFT100M_IVF4096,PQ16_23_banks"
  # GT_DIR: "/mnt/scratch/wenqi/saved_npy_data/gnd/"

  # FPGA Settings
  DEVICE: U280 # Supported devices: U280, U250, U50
  FREQ: 140
