---

    # 
  # 
  # ======== Result =========
  # 
  # best option name OPQ16,IVF4096,PQ16
  # nprobe: 3
  # QPS 31876.138433515483
  # stage_option_list
  # Stage 1:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 37
  #         URAM: 0
  #         FF: 2659
  #         LUT: 2152
  #         DSP48E: 20
  #         
  # QPS: 32014.635261833984
  # Cycles per query: 4373.0
  # OPQ_ENABLE: True
  # OPQ_UNROLL_FACTOR: 4
  # Stage 2:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 1.0
  #         URAM: 128.0
  #         FF: 184199
  #         LUT: 143310
  #         DSP48E: 928
  #         
  # QPS: 33065.658951346246
  # Cycles per query: 4234
  # STAGE2_ON_CHIP: True
  # STAGE2_OFF_CHIP_START_CHANNEL:None
  # PE_NUM_CENTER_DIST_COMP: 16
  # Stage 3:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 6.0
  #         URAM: 0
  #         FF: 2334.63
  #         LUT: 2263.41
  #         DSP48E: 0
  #         
  # QPS: 34071.550255536626
  # Cycles per query: 4109
  # STAGE_3_PRIORITY_QUEUE_LEVEL: 2
  # STAGE_3_PRIORITY_QUEUE_L1_NUM: 2
  # Stage 4:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 73.0
  #         URAM: 88
  #         FF: 25583
  #         LUT: 20487
  #         DSP48E: 162
  #         
  # QPS: 31876.138433515483
  # Cycles per query: 4392
  # PE_NUM_TABLE_CONSTRUCTION: 3
  # Stage 5:
  # 
  #         HBM_bank: 9.0
  #         BRAM_18K: 567.0
  #         URAM: 0.0
  #         FF: 158787.0
  #         LUT: 147726.0
  #         DSP48E: 810.0
  #         
  # QPS: 34238.20004891171
  # Cycles per query: 4089
  # HBM_CHANNEL_NUM: 9
  # STAGE5_COMP_PE_NUM: 27
  # Stage 6:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 110.0
  #         URAM: 0
  #         FF: 21233.85
  #         LUT: 17791.95
  #         DSP48E: 0
  #         
  # QPS: 45766.59038901602
  # Cycles per query: 3059
  # 
  # SORT_GROUP_ENABLE: False
  # SORT_GROUP_NUM: None
  # STAGE_6_PRIORITY_QUEUE_LEVEL: 2
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: None
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: None
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: None
  #         
  # total_valid_design: 31990742
  # Total resource consumption: (with shell)
  # 
  #         HBM_bank: 9.0
  #         BRAM_18K: 1234.0
  #         URAM: 216.0
  #         FF: 718940.48
  #         LUT: 527491.3600000001
  #         DSP48E: 1924.0
  #         
  # Total resource consumption: (accelerator kernel without shell)
  # 
  #         HBM_bank: 9.0
  #         BRAM_18K: 794.0
  #         URAM: 216.0
  #         FF: 394796.48
  #         LUT: 333730.36000000004
  #         DSP48E: 1920.0
  #         
  # 
  # Per Stage Utilization rate (Total = FPGA):
  # Stage 1: {'BRAM_18K': '0.9176587301587302%', 'DSP48E': '0.22163120567375888%', 'FF': '0.10198054737358862%', 'LUT': '0.16507118311242022%', 'URAM': '0.0%'}
  # Stage 2: {'BRAM_18K': '0.0248015873015873%', 'DSP48E': '10.28368794326241%', 'FF': '7.064578730976927%', 'LUT': '10.992728276877761%', 'URAM': '13.333333333333334%'}
  # Stage 3: {'BRAM_18K': '0.1488095238095238%', 'DSP48E': '0.0%', 'FF': '0.08953999447717231%', 'LUT': '0.17361699189985272%', 'URAM': '0.0%'}
  # Stage 4: {'BRAM_18K': '1.8105158730158732%', 'DSP48E': '1.795212765957447%', 'FF': '0.9811840328915071%', 'LUT': '1.5714745949926363%', 'URAM': '9.166666666666666%'}
  # Stage 5: {'BRAM_18K': '14.0625%', 'DSP48E': '8.976063829787234%', 'FF': '6.089953055964654%', 'LUT': '11.331461708394698%', 'URAM': '0.0%'}
  # Stage 6: {'BRAM_18K': '2.7281746031746033%', 'DSP48E': '0.0%', 'FF': '0.8143812131811488%', 'LUT': '1.3647482511045657%', 'URAM': '0.0%'}
  # 
  # Per Stage Utilization rate (Total = Accelerator Kernel (without shell)):
  # Stage 1: {'BRAM_18K': '4.659949622166247%', 'DSP48E': '1.0416666666666665%', 'FF': '0.6735115774081877%', 'LUT': '0.6448319535567576%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 1: 0.6448319535567576%
  # Stage 2: {'BRAM_18K': '0.12594458438287154%', 'DSP48E': '48.333333333333336%', 'FF': '46.656697648368095%', 'LUT': '42.941852817945595%', 'URAM': '59.25925925925925%'}
  # LUT only:
  # Stage 2: 42.941852817945595%
  # Stage 3: {'BRAM_18K': '0.7556675062972292%', 'DSP48E': '0.0%', 'FF': '0.5913502572262043%', 'LUT': '0.6782151914497679%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 3: 0.6782151914497679%
  # Stage 4: {'BRAM_18K': '9.193954659949624%', 'DSP48E': '8.4375%', 'FF': '6.480047643788517%', 'LUT': '6.138788212136288%', 'URAM': '40.74074074074074%'}
  # LUT only:
  # Stage 4: 6.138788212136288%
  # Stage 5: {'BRAM_18K': '71.41057934508817%', 'DSP48E': '42.1875%', 'FF': '40.21996346066713%', 'LUT': '44.265076752381766%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 5: 44.265076752381766%
  # Stage 6: {'BRAM_18K': '13.85390428211587%', 'DSP48E': '0.0%', 'FF': '5.378429412541875%', 'LUT': '5.331235072529811%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 6: 5.331235072529811%
  # 
  # Total Utilization rate:
  # {'BRAM_18K': '30.60515873015873%', 'DSP48E': '21.320921985815602%', 'FF': '27.57350270004909%', 'LUT': '40.46172066764851%', 'URAM': '22.5%'}


  # Constants
  NLIST: 4096
  NPROBE: 3
  D: 128
  M: 16
  K: 256
  TOPK: 1

  QUERY_NUM: 10000

  LARGE_NUM: 99999999 # used to init the heap
  # stage 1
  OPQ_ENABLE: True
  OPQ_UNROLL_FACTOR: 4 # 4 or 8, the larger the better performance, left None if OPQ_ENABLE=False, only used when OPQ_ENABLE=True

  # stage 2
  # except last PE: compute more distances per query, last one compute less
  # e.g., nlist = 8192, PE num = 15, 
  #   each of the first 14 PEs construct 547 tables (8192 / 15 round up), 
  #   while the last constructs 534: 14 * 547 + 534 = 8192
  STAGE2_ON_CHIP: True
  PE_NUM_CENTER_DIST_COMP: 16

  # stage 3
  STAGE_3_PRIORITY_QUEUE_LEVEL: 2 # support 1 or 2
  STAGE_3_PRIORITY_QUEUE_L1_NUM: 2 # only used when STAGE_3_PRIORITY_QUEUE_LEVEL=2

  # stage 4
  # except last PE: construct more tables per query, last one construct less
  # e.g., nprobe = 17, PE num = 6, each of the first 5 PEs construct 3 tables, 
  #   while the last constructs 2: 5 * 3 + 2 = 17
  PE_NUM_TABLE_CONSTRUCTION: 3

  # stage 5
  # (HBM_CHANNEL_NUM * 3 / STAGE5_COMP_PE_NUM) must be integar
  # e.g., default 1 HBM channel -> 3 PQ code streams -> STAGE5_COMP_PE_NUM = 3 * HBM_CHANNEL_NUM
  # e.g., merge content of 1 HBM channel to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM
  # e.g., merge content of 2 HBM channels to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM / 2
  HBM_CHANNEL_NUM: 9 # PQ code stream num = 3 * HBM_CHANNEL_NUM
  STAGE5_COMP_PE_NUM: 27

  # stage 6
  # there could be a sorting network before the priority queue group (SORT_GROUP_ENABLE)
  #   if not, set SORT_GROUP_ENABLE to False, and SORT_GROUP_NUM to 0 or None
  # number of 16 outputs per cycle, e.g., HBM channel num = 10, comp PE num = 30, then 
  #   SORT_GROUP_NUM = 2; if HBM channel = 12, PE_num = 36, then SORT_GROUP_NUM = 3
  SORT_GROUP_ENABLE: False
  SORT_GROUP_NUM: 0 # only used when SORT_GROUP_ENABLE=True
  STAGE_6_PRIORITY_QUEUE_LEVEL: 2 # supported level num: 2 or 3
  # only fill STAGE_6_PRIORITY_QUEUE_L2_NUM, STAGE_6_STREAM_PER_L2_QUEUE_LARGER, STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  #   when STAGE_6_PRIORITY_QUEUE_LEVEL = 3, else left them blank
  # Must subject to: L1 stream num = (without sort-reduction unit) STAGE5_COMP_PE_NUM * 2 
  #                  or = (with sort reduction) 16 * 2
  # (STAGE_6_PRIORITY_QUEUE_L2_NUM - 1) * STAGE_6_STREAM_PER_L2_QUEUE_LARGER + STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: 2 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: 6 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: 4 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3

  # Dataset config
  DB_SCALE: 100M # 1M to 1000M
  FPGA_NUM: 1 # e.g., can use 8 FPGAs to serve 1000M dataset, each stores 125M vectors

  # Data directory (don't add "/" after the dir)
  #   e.g., dir=/home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks, 
  #     then the content for HBM0 is:
  #     /home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks/HBM_bank_0_raw
  # DATA_DIR: "/mnt/scratch/wenqi/saved_npy_data/FPGA_data_SIFT100M_IVF4096,PQ16_23_banks"
  # GT_DIR: "/mnt/scratch/wenqi/saved_npy_data/gnd/"

  # FPGA Settings
  DEVICE: U280 # Supported devices: U280, U250, U50
  FREQ: 140
