---
# U280_SIFT100M_K1_R20_55perc_140MHz_with_network

# best option name IVF1024,PQ16
# nprobe: 1
# QPS 31876.138433515483
# stage_option_list
# Stage 2:

#         HBM_bank: 0
#         BRAM_18K: 1.0
#         URAM: 32.0
#         FF: 46139
#         LUT: 35958
#         DSP48E: 232
        
# QPS: 33065.658951346246
# Cycles per query: 4234
# STAGE2_ON_CHIP: True
# STAGE2_OFF_CHIP_START_CHANNEL:None
# PE_NUM_CENTER_DIST_COMP: 4
# Stage 3:

#         HBM_bank: 0
#         BRAM_18K: 1.0
#         URAM: 0
#         FF: 291.07
#         LUT: 269.49
#         DSP48E: 0
        
# QPS: 67994.17192812046
# Cycles per query: 2059
# STAGE_3_PRIORITY_QUEUE_LEVEL: 1
# STAGE_3_PRIORITY_QUEUE_L1_NUM: 1
# Stage 4:

#         HBM_bank: 0
#         BRAM_18K: 35.0
#         URAM: 24
#         FF: 9541
#         LUT: 7405
#         DSP48E: 54
        
# QPS: 31876.138433515483
# Cycles per query: 4392
# PE_NUM_TABLE_CONSTRUCTION: 1
# Stage 5:

#         HBM_bank: 9.0
#         BRAM_18K: 567.0
#         URAM: 0.0
#         FF: 158787.0
#         LUT: 147726.0
#         DSP48E: 810.0
        
# QPS: 32295.271049596307
# Cycles per query: 4335
# HBM_CHANNEL_NUM: 9
# STAGE5_COMP_PE_NUM: 27
# Stage 6:

#         HBM_bank: 0
#         BRAM_18K: 110.0
#         URAM: 0
#         FF: 21233.85
#         LUT: 17791.95
#         DSP48E: 0
        
# QPS: 35008.75218804701
# Cycles per query: 3999

# SORT_GROUP_ENABLE: False
# SORT_GROUP_NUM: None
# STAGE_6_PRIORITY_QUEUE_LEVEL: 2
# STAGE_6_PRIORITY_QUEUE_L2_NUM: None
# STAGE_6_STREAM_PER_L2_QUEUE_LARGER: None
# STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: None
        
# total_valid_design: 26252280
# Total resource consumption:

#         HBM_bank: 9.0
#         BRAM_18K: 2083.0
#         URAM: 74.0
#         FF: 823829.92
#         LUT: 560307.44
#         DSP48E: 1100.0
        
# Utilization rate:
# {'BRAM_18K': '51.66170634920635%', 'DSP48E': '12.189716312056738%', 'FF': '31.596324251350026%', 'LUT': '42.978908934707896%', 'URAM': '7.708333333333334%'}


  # Constants
  NLIST: 1024
  NPROBE: 1
  D: 128
  M: 16
  K: 256
  TOPK: 1

  QUERY_NUM: 10000

  LARGE_NUM: 99999999 # used to init the heap
  # stage 1
  OPQ_ENABLE: False
  OPQ_UNROLL_FACTOR: 4 # 4 or 8, the larger the better performance, left None if OPQ_ENABLE=False, only used when OPQ_ENABLE=True

  # stage 2
  # except last PE: compute more distances per query, last one compute less
  # e.g., nlist = 8192, PE num = 15, 
  #   each of the first 14 PEs construct 547 tables (8192 / 15 round up), 
  #   while the last constructs 534: 14 * 547 + 534 = 8192
  STAGE2_ON_CHIP: True
  STAGE2_OFF_CHIP_START_CHANNEL: None # Only used when STAGE2_ON_CHIP = True
  PE_NUM_CENTER_DIST_COMP: 4

  # stage 3
  STAGE_3_PRIORITY_QUEUE_LEVEL: 1 # support 1 or 2
  STAGE_3_PRIORITY_QUEUE_L1_NUM: 1 # only used when STAGE_3_PRIORITY_QUEUE_LEVEL=2

  # stage 4
  # except last PE: construct more tables per query, last one construct less
  # e.g., nprobe = 17, PE num = 6, each of the first 5 PEs construct 3 tables, 
  #   while the last constructs 2: 5 * 3 + 2 = 17
  PE_NUM_TABLE_CONSTRUCTION: 1

  # stage 5
  # (HBM_CHANNEL_NUM * 3 / STAGE5_COMP_PE_NUM) must be integar
  # e.g., default 1 HBM channel -> 3 PQ code streams -> STAGE5_COMP_PE_NUM = 3 * HBM_CHANNEL_NUM
  # e.g., merge content of 1 HBM channel to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM
  # e.g., merge content of 2 HBM channels to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM / 2
  HBM_CHANNEL_NUM: 9 # PQ code stream num = 3 * HBM_CHANNEL_NUM
  STAGE5_COMP_PE_NUM: 27

  # stage 6
  # there could be a sorting network before the priority queue group (SORT_GROUP_ENABLE)
  #   if not, set SORT_GROUP_ENABLE to False, and SORT_GROUP_NUM to 0 or None
  # number of 16 outputs per cycle, e.g., HBM channel num = 10, comp PE num = 30, then 
  #   SORT_GROUP_NUM = 2; if HBM channel = 12, PE_num = 36, then SORT_GROUP_NUM = 3
  SORT_GROUP_ENABLE: False
  SORT_GROUP_NUM: None # only used when SORT_GROUP_ENABLE=True
  STAGE_6_PRIORITY_QUEUE_LEVEL: 2 # supported level num: 2 or 3
  # only fill STAGE_6_PRIORITY_QUEUE_L2_NUM, STAGE_6_STREAM_PER_L2_QUEUE_LARGER, STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  #   when STAGE_6_PRIORITY_QUEUE_LEVEL = 3, else left them blank
  # Must subject to: L1 stream num = (without sort-reduction unit) STAGE5_COMP_PE_NUM * 2 
  #                  or = (with sort reduction) 16 * 2
  # (STAGE_6_PRIORITY_QUEUE_L2_NUM - 1) * STAGE_6_STREAM_PER_L2_QUEUE_LARGER + STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: 2 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: 6 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: 4 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3

  # Dataset config
  DB_SCALE: "100M" # 1M to 1000M

  # Data directory (don't add "/" after the dir)
  #   e.g., dir=/home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks, 
  #     then the content for HBM0 is:
  #     /home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks/HBM_bank_0_raw
  DATA_DIR: "/mnt/scratch/wenqi/saved_npy_data/FPGA_data_SIFT100M_IVF1024,PQ16_9_banks"
  GT_DIR: "/mnt/scratch/wenqi/saved_npy_data/gnd/"

  # FPGA Settings
  DEVICE: U280 # Supported devices: U280, U250, U50
  FREQ: 140