---

    # 
  # 
  # ======== Result =========
  # 
  # best option name nlist_8192_nprobe_17_OPQ_1
  # nprobe: 17
  # QPS 10129.513059836481
  # stage_option_list
  # Stage 1:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 37
  #         URAM: 0
  #         FF: 2659
  #         LUT: 2152
  #         DSP48E: 20
  #         
  # QPS: 32014.635261833984
  # Cycles per query: 4373.0
  # OPQ_ENABLE: True
  # OPQ_UNROLL_FACTOR: 4
  # Stage 2:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 1.0
  #         URAM: 160.0
  #         FF: 115169
  #         LUT: 89634
  #         DSP48E: 580
  #         
  # QPS: 10569.22844632342
  # Cycles per query: 13246
  # STAGE2_ON_CHIP: True
  # STAGE2_OFF_CHIP_START_CHANNEL:None
  # PE_NUM_CENTER_DIST_COMP: 10
  # Stage 3:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 6.0
  #         URAM: 0
  #         FF: 10569.57
  #         LUT: 11313.99
  #         DSP48E: 0
  #         
  # QPS: 17033.702396885266
  # Cycles per query: 8219
  # STAGE_3_PRIORITY_QUEUE_LEVEL: 2
  # STAGE_3_PRIORITY_QUEUE_L1_NUM: 2
  # Stage 4:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 226.0
  #         URAM: 176
  #         FF: 58766
  #         LUT: 45294
  #         DSP48E: 324
  #         
  # QPS: 10835.913312693498
  # Cycles per query: 12920
  # PE_NUM_TABLE_CONSTRUCTION: 6
  # Stage 5:
  # 
  #         HBM_bank: 10.0
  #         BRAM_18K: 630.0
  #         URAM: 0.0
  #         FF: 176430.0
  #         LUT: 164140.0
  #         DSP48E: 900.0
  #         
  # QPS: 10129.513059836481
  # Cycles per query: 13821
  # HBM_CHANNEL_NUM: 10
  # STAGE5_COMP_PE_NUM: 30
  # Stage 6:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 122.0
  #         URAM: 0
  #         FF: 250795.39999999997
  #         LUT: 269485.8
  #         DSP48E: 0
  #         
  # QPS: 17721.518987341773
  # Cycles per query: 7900
  # 
  # SORT_GROUP_ENABLE: False
  # SORT_GROUP_NUM: None
  # STAGE_6_PRIORITY_QUEUE_LEVEL: 2
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: None
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: None
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: None
  #         
  # total_valid_design: 983966
  # Total resource consumption: (with shell)
  # 
  #         HBM_bank: 10.0
  #         BRAM_18K: 1462.0
  #         URAM: 336.0
  #         FF: 938532.97
  #         LUT: 775780.79
  #         DSP48E: 1828.0
  #         
  # Total resource consumption: (accelerator kernel without shell)
  # 
  #         HBM_bank: 10.0
  #         BRAM_18K: 1022.0
  #         URAM: 336.0
  #         FF: 614388.97
  #         LUT: 582019.79
  #         DSP48E: 1824.0
  #         
  # 
  # Per Stage Utilization rate (Total = FPGA):
  # Stage 1: {'BRAM_18K': '0.9176587301587302%', 'DSP48E': '0.22163120567375888%', 'FF': '0.10198054737358862%', 'LUT': '0.16507118311242022%', 'URAM': '0.0%'}
  # Stage 2: {'BRAM_18K': '0.0248015873015873%', 'DSP48E': '6.427304964539007%', 'FF': '4.417073208149239%', 'LUT': '6.875460235640649%', 'URAM': '16.666666666666664%'}
  # Stage 3: {'BRAM_18K': '0.1488095238095238%', 'DSP48E': '0.0%', 'FF': '0.4053744016936671%', 'LUT': '0.8678502393225331%', 'URAM': '0.0%'}
  # Stage 4: {'BRAM_18K': '5.60515873015873%', 'DSP48E': '3.590425531914894%', 'FF': '2.2538506381934216%', 'LUT': '3.4743188512518413%', 'URAM': '18.333333333333332%'}
  # Stage 5: {'BRAM_18K': '15.625%', 'DSP48E': '9.97340425531915%', 'FF': '6.766614506627393%', 'LUT': '12.590513009327442%', 'URAM': '0.0%'}
  # Stage 6: {'BRAM_18K': '3.0257936507936507%', 'DSP48E': '0.0%', 'FF': '9.618748465881197%', 'LUT': '20.671161634756995%', 'URAM': '0.0%'}
  # 
  # Per Stage Utilization rate (Total = Accelerator Kernel (without shell)):
  # Stage 1: {'BRAM_18K': '3.6203522504892365%', 'DSP48E': '1.0964912280701753%', 'FF': '0.43278771752689504%', 'LUT': '0.3697468775073782%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 1: 0.3697468775073782%
  # Stage 2: {'BRAM_18K': '0.09784735812133072%', 'DSP48E': '31.798245614035086%', 'FF': '18.74529095143098%', 'LUT': '15.400507257665586%', 'URAM': '47.61904761904761%'}
  # LUT only:
  # Stage 2: 15.400507257665586%
  # Stage 3: {'BRAM_18K': '0.5870841487279843%', 'DSP48E': '0.0%', 'FF': '1.7203385015196482%', 'LUT': '1.943918436175512%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 3: 1.943918436175512%
  # Stage 4: {'BRAM_18K': '22.113502935420744%', 'DSP48E': '17.763157894736842%', 'FF': '9.56495036035559%', 'LUT': '7.782209604934567%', 'URAM': '52.38095238095239%'}
  # LUT only:
  # Stage 4: 7.782209604934567%
  # Stage 5: {'BRAM_18K': '61.64383561643836%', 'DSP48E': '49.34210526315789%', 'FF': '28.71633584177138%', 'LUT': '28.20179018311387%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 5: 28.20179018311387%
  # Stage 6: {'BRAM_18K': '11.937377690802348%', 'DSP48E': '0.0%', 'FF': '40.8202966273955%', 'LUT': '46.30182764060308%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 6: 46.30182764060308%
  # 
  # Total Utilization rate:
  # {'BRAM_18K': '36.25992063492063%', 'DSP48E': '20.25709219858156%', 'FF': '35.9955268931026%', 'LUT': '59.50699481467845%', 'URAM': '35.0%'}


  # Constants
  NLIST: 8192
  NPROBE: 17
  D: 128
  M: 16
  K: 256
  TOPK: 20

  QUERY_NUM: 10000

  LARGE_NUM: 99999999 # used to init the heap
  # stage 1
  OPQ_ENABLE: 1
  OPQ_UNROLL_FACTOR: 4 # 4 or 8, the larger the better performance, left None if OPQ_ENABLE=False, only used when OPQ_ENABLE=True

  # stage 2
  # except last PE: compute more distances per query, last one compute less
  # e.g., nlist = 8192, PE num = 15, 
  #   each of the first 14 PEs construct 547 tables (8192 / 15 round up), 
  #   while the last constructs 534: 14 * 547 + 534 = 8192
  STAGE2_ON_CHIP: True
  PE_NUM_CENTER_DIST_COMP: 10

  # stage 3
  STAGE_3_PRIORITY_QUEUE_LEVEL: 2 # support 1 or 2
  STAGE_3_PRIORITY_QUEUE_L1_NUM: 2 # only used when STAGE_3_PRIORITY_QUEUE_LEVEL=2

  # stage 4
  # except last PE: construct more tables per query, last one construct less
  # e.g., nprobe = 17, PE num = 6, each of the first 5 PEs construct 3 tables, 
  #   while the last constructs 2: 5 * 3 + 2 = 17
  PE_NUM_TABLE_CONSTRUCTION: 6

  # stage 5
  # (HBM_CHANNEL_NUM * 3 / STAGE5_COMP_PE_NUM) must be integar
  # e.g., default 1 HBM channel -> 3 PQ code streams -> STAGE5_COMP_PE_NUM = 3 * HBM_CHANNEL_NUM
  # e.g., merge content of 1 HBM channel to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM
  # e.g., merge content of 2 HBM channels to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM / 2
  HBM_CHANNEL_NUM: 10 # PQ code stream num = 3 * HBM_CHANNEL_NUM
  STAGE5_COMP_PE_NUM: 30

  # stage 6
  # there could be a sorting network before the priority queue group (SORT_GROUP_ENABLE)
  #   if not, set SORT_GROUP_ENABLE to False, and SORT_GROUP_NUM to 0 or None
  # number of 16 outputs per cycle, e.g., HBM channel num = 10, comp PE num = 30, then 
  #   SORT_GROUP_NUM = 2; if HBM channel = 12, PE_num = 36, then SORT_GROUP_NUM = 3
  SORT_GROUP_ENABLE: False
  SORT_GROUP_NUM: 0 # only used when SORT_GROUP_ENABLE=True
  STAGE_6_PRIORITY_QUEUE_LEVEL: 2 # supported level num: 2 or 3
  # only fill STAGE_6_PRIORITY_QUEUE_L2_NUM, STAGE_6_STREAM_PER_L2_QUEUE_LARGER, STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  #   when STAGE_6_PRIORITY_QUEUE_LEVEL = 3, else left them blank
  # Must subject to: L1 stream num = (without sort-reduction unit) STAGE5_COMP_PE_NUM * 2 
  #                  or = (with sort reduction) 16 * 2
  # (STAGE_6_PRIORITY_QUEUE_L2_NUM - 1) * STAGE_6_STREAM_PER_L2_QUEUE_LARGER + STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: 2 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: 6 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: 4 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3

  # Dataset config
  DB_SCALE: 100M # 1M to 1000M
  FPGA_NUM: 1 # e.g., can use 8 FPGAs to serve 1000M dataset, each stores 125M vectors

  # Data directory (don't add "/" after the dir)
  #   e.g., dir=/home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks, 
  #     then the content for HBM0 is:
  #     /home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks/HBM_bank_0_raw
  # DATA_DIR: "/mnt/scratch/wenqi/saved_npy_data/FPGA_data_SIFT100M_IVF4096,PQ16_23_banks"
  # GT_DIR: "/mnt/scratch/wenqi/saved_npy_data/gnd/"

  # FPGA Settings
  DEVICE: U280 # Supported devices: U280, U250, U50
  FREQ: 140
