---

    # 
  # 
  # ======== Result =========
  # 
  # best option name OPQ16,IVF16384,PQ16
  # nprobe: 21
  # QPS 8473.550417624985
  # stage_option_list
  # Stage 1:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 37
  #         URAM: 0
  #         FF: 2659
  #         LUT: 2152
  #         DSP48E: 20
  #         
  # QPS: 32014.635261833984
  # Cycles per query: 4373.0
  # OPQ_ENABLE: True
  # OPQ_UNROLL_FACTOR: 4
  # Stage 2:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 1.0
  #         URAM: 256.0
  #         FF: 184199
  #         LUT: 143310
  #         DSP48E: 928
  #         
  # QPS: 8473.550417624985
  # Cycles per query: 16522
  # STAGE2_ON_CHIP: True
  # STAGE2_OFF_CHIP_START_CHANNEL:None
  # PE_NUM_CENTER_DIST_COMP: 16
  # Stage 3:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 6.0
  #         URAM: 0
  #         FF: 12922.41
  #         LUT: 13899.869999999999
  #         DSP48E: 0
  #         
  # QPS: 8528.784648187633
  # Cycles per query: 16415
  # STAGE_3_PRIORITY_QUEUE_LEVEL: 2
  # STAGE_3_PRIORITY_QUEUE_L1_NUM: 2
  # Stage 4:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 261.0
  #         URAM: 312
  #         FF: 68307
  #         LUT: 52699
  #         DSP48E: 378
  #         
  # QPS: 10835.913312693498
  # Cycles per query: 12920
  # PE_NUM_TABLE_CONSTRUCTION: 7
  # Stage 5:
  # 
  #         HBM_bank: 16.0
  #         BRAM_18K: 336.0
  #         URAM: 0.0
  #         FF: 94096.0
  #         LUT: 87541.33333333333
  #         DSP48E: 480.0
  #         
  # QPS: 8591.06529209622
  # Cycles per query: 16296
  # HBM_CHANNEL_NUM: 16
  # STAGE5_COMP_PE_NUM: 16
  # Stage 6:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 66.0
  #         URAM: 0
  #         FF: 70973.09999999999
  #         LUT: 74675.7
  #         DSP48E: 0
  #         
  # QPS: 15118.790496760259
  # Cycles per query: 9260
  # 
  # SORT_GROUP_ENABLE: False
  # SORT_GROUP_NUM: None
  # STAGE_6_PRIORITY_QUEUE_LEVEL: 2
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: None
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: None
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: None
  #         
  # total_valid_design: 402248
  # Total resource consumption: (with shell)
  # 
  #         HBM_bank: 16.0
  #         BRAM_18K: 1147.0
  #         URAM: 568.0
  #         FF: 757300.51
  #         LUT: 568038.9033333333
  #         DSP48E: 1810.0
  #         
  # Total resource consumption: (accelerator kernel without shell)
  # 
  #         HBM_bank: 16.0
  #         BRAM_18K: 707.0
  #         URAM: 568.0
  #         FF: 433156.51
  #         LUT: 374277.9033333333
  #         DSP48E: 1806.0
  #         
  # 
  # Per Stage Utilization rate (Total = FPGA):
  # Stage 1: {'BRAM_18K': '0.9176587301587302%', 'DSP48E': '0.22163120567375888%', 'FF': '0.10198054737358862%', 'LUT': '0.16507118311242022%', 'URAM': '0.0%'}
  # Stage 2: {'BRAM_18K': '0.0248015873015873%', 'DSP48E': '10.28368794326241%', 'FF': '7.064578730976927%', 'LUT': '10.992728276877761%', 'URAM': '26.666666666666668%'}
  # Stage 3: {'BRAM_18K': '0.1488095238095238%', 'DSP48E': '0.0%', 'FF': '0.49561280375552286%', 'LUT': '1.066202595729013%', 'URAM': '0.0%'}
  # Stage 4: {'BRAM_18K': '6.4732142857142865%', 'DSP48E': '4.1888297872340425%', 'FF': '2.6197763254786453%', 'LUT': '4.042326337751596%', 'URAM': '32.5%'}
  # Stage 5: {'BRAM_18K': '8.333333333333332%', 'DSP48E': '5.319148936170213%', 'FF': '3.608861070201276%', 'LUT': '6.714940271641303%', 'URAM': '0.0%'}
  # Stage 6: {'BRAM_18K': '1.636904761904762%', 'DSP48E': '0.0%', 'FF': '2.722029178939617%', 'LUT': '5.7280697717231215%', 'URAM': '0.0%'}
  # 
  # Per Stage Utilization rate (Total = Accelerator Kernel (without shell)):
  # Stage 1: {'BRAM_18K': '5.233380480905233%', 'DSP48E': '1.1074197120708749%', 'FF': '0.6138658749466791%', 'LUT': '0.5749738311650796%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 1: 0.5749738311650796%
  # Stage 2: {'BRAM_18K': '0.14144271570014144%', 'DSP48E': '51.38427464008859%', 'FF': '42.52481395235177%', 'LUT': '38.2897303644366%', 'URAM': '45.07042253521127%'}
  # LUT only:
  # Stage 2: 38.2897303644366%
  # Stage 3: {'BRAM_18K': '0.8486562942008486%', 'DSP48E': '0.0%', 'FF': '2.9833119673071518%', 'LUT': '3.713783227972377%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 3: 3.713783227972377%
  # Stage 4: {'BRAM_18K': '36.916548797736915%', 'DSP48E': '20.930232558139537%', 'FF': '15.769588687470032%', 'LUT': '14.080179334836679%', 'URAM': '54.929577464788736%'}
  # LUT only:
  # Stage 4: 14.080179334836679%
  # Stage 5: {'BRAM_18K': '47.524752475247524%', 'DSP48E': '26.578073089701%', 'FF': '21.72332582511573%', 'LUT': '23.389393964668194%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 5: 23.389393964668194%
  # Stage 6: {'BRAM_18K': '9.335219236209335%', 'DSP48E': '0.0%', 'FF': '16.38509369280863%', 'LUT': '19.951939276921067%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 6: 19.951939276921067%
  # 
  # Total Utilization rate:
  # {'BRAM_18K': '28.447420634920633%', 'DSP48E': '20.05762411347518%', 'FF': '29.04472378190967%', 'LUT': '43.57195809810178%', 'URAM': '59.166666666666664%'}


  # Constants
  NLIST: 16384
  NPROBE: 21
  D: 128
  M: 16
  K: 256
  TOPK: 10

  QUERY_NUM: 10000

  LARGE_NUM: 99999999 # used to init the heap
  # stage 1
  OPQ_ENABLE: True
  OPQ_UNROLL_FACTOR: 4 # 4 or 8, the larger the better performance, left None if OPQ_ENABLE=False, only used when OPQ_ENABLE=True

  # stage 2
  # except last PE: compute more distances per query, last one compute less
  # e.g., nlist = 8192, PE num = 15, 
  #   each of the first 14 PEs construct 547 tables (8192 / 15 round up), 
  #   while the last constructs 534: 14 * 547 + 534 = 8192
  STAGE2_ON_CHIP: True
  PE_NUM_CENTER_DIST_COMP: 16

  # stage 3
  STAGE_3_PRIORITY_QUEUE_LEVEL: 2 # support 1 or 2
  STAGE_3_PRIORITY_QUEUE_L1_NUM: 2 # only used when STAGE_3_PRIORITY_QUEUE_LEVEL=2

  # stage 4
  # except last PE: construct more tables per query, last one construct less
  # e.g., nprobe = 17, PE num = 6, each of the first 5 PEs construct 3 tables, 
  #   while the last constructs 2: 5 * 3 + 2 = 17
  PE_NUM_TABLE_CONSTRUCTION: 7

  # stage 5
  # (HBM_CHANNEL_NUM * 3 / STAGE5_COMP_PE_NUM) must be integar
  # e.g., default 1 HBM channel -> 3 PQ code streams -> STAGE5_COMP_PE_NUM = 3 * HBM_CHANNEL_NUM
  # e.g., merge content of 1 HBM channel to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM
  # e.g., merge content of 2 HBM channels to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM / 2
  HBM_CHANNEL_NUM: 16 # PQ code stream num = 3 * HBM_CHANNEL_NUM
  STAGE5_COMP_PE_NUM: 16

  # stage 6
  # there could be a sorting network before the priority queue group (SORT_GROUP_ENABLE)
  #   if not, set SORT_GROUP_ENABLE to False, and SORT_GROUP_NUM to 0 or None
  # number of 16 outputs per cycle, e.g., HBM channel num = 10, comp PE num = 30, then 
  #   SORT_GROUP_NUM = 2; if HBM channel = 12, PE_num = 36, then SORT_GROUP_NUM = 3
  SORT_GROUP_ENABLE: False
  SORT_GROUP_NUM: 0 # only used when SORT_GROUP_ENABLE=True
  STAGE_6_PRIORITY_QUEUE_LEVEL: 2 # supported level num: 2 or 3
  # only fill STAGE_6_PRIORITY_QUEUE_L2_NUM, STAGE_6_STREAM_PER_L2_QUEUE_LARGER, STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  #   when STAGE_6_PRIORITY_QUEUE_LEVEL = 3, else left them blank
  # Must subject to: L1 stream num = (without sort-reduction unit) STAGE5_COMP_PE_NUM * 2 
  #                  or = (with sort reduction) 16 * 2
  # (STAGE_6_PRIORITY_QUEUE_L2_NUM - 1) * STAGE_6_STREAM_PER_L2_QUEUE_LARGER + STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: 2 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: 6 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: 4 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3

  # Dataset config
  DB_SCALE: 100M # 1M to 1000M
  FPGA_NUM: 1 # e.g., can use 8 FPGAs to serve 1000M dataset, each stores 125M vectors

  # Data directory (don't add "/" after the dir)
  #   e.g., dir=/home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks, 
  #     then the content for HBM0 is:
  #     /home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks/HBM_bank_0_raw
  # DATA_DIR: "/mnt/scratch/wenqi/saved_npy_data/FPGA_data_SIFT100M_IVF4096,PQ16_23_banks"
  # GT_DIR: "/mnt/scratch/wenqi/saved_npy_data/gnd/"

  # FPGA Settings
  DEVICE: U280 # Supported devices: U280, U250, U50
  FREQ: 140
