---

    # 
  # 
  # ======== Result =========
  # 
  # best option name nlist_8192_nprobe_17_OPQ_1
  # nprobe: 17
  # QPS 11883.541295306002
  # stage_option_list
  # Stage 1:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 37
  #         URAM: 0
  #         FF: 2659
  #         LUT: 2152
  #         DSP48E: 20
  #         
  # QPS: 32014.635261833984
  # Cycles per query: 4373.0
  # OPQ_ENABLE: True
  # OPQ_UNROLL_FACTOR: 4
  # Stage 2:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 1.0
  #         URAM: 192.0
  #         FF: 138179
  #         LUT: 107526
  #         DSP48E: 696
  #         
  # QPS: 12655.939251491593
  # Cycles per query: 11062
  # STAGE2_ON_CHIP: True
  # STAGE2_OFF_CHIP_START_CHANNEL:None
  # PE_NUM_CENTER_DIST_COMP: 12
  # Stage 3:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 6.0
  #         URAM: 0
  #         FF: 10569.57
  #         LUT: 11313.99
  #         DSP48E: 0
  #         
  # QPS: 17033.702396885266
  # Cycles per query: 8219
  # STAGE_3_PRIORITY_QUEUE_LEVEL: 2
  # STAGE_3_PRIORITY_QUEUE_L1_NUM: 2
  # Stage 4:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 331.0
  #         URAM: 200
  #         FF: 87389
  #         LUT: 67509
  #         DSP48E: 486
  #         
  # QPS: 16173.752310536043
  # Cycles per query: 8656
  # PE_NUM_TABLE_CONSTRUCTION: 9
  # Stage 5:
  # 
  #         HBM_bank: 14.0
  #         BRAM_18K: 882.0
  #         URAM: 0.0
  #         FF: 247002.0
  #         LUT: 229796.0
  #         DSP48E: 1260.0
  #         
  # QPS: 11883.541295306002
  # Cycles per query: 11781
  # HBM_CHANNEL_NUM: 14
  # STAGE5_COMP_PE_NUM: 42
  # Stage 6:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 170.0
  #         URAM: 0
  #         FF: 32815.95
  #         LUT: 27496.65
  #         DSP48E: 0
  #         
  # QPS: 24835.905623558632
  # Cycles per query: 5637
  # 
  # SORT_GROUP_ENABLE: False
  # SORT_GROUP_NUM: None
  # STAGE_6_PRIORITY_QUEUE_LEVEL: 2
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: None
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: None
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: None
  #         
  # total_valid_design: 1235484
  # Total resource consumption: (with shell)
  # 
  #         HBM_bank: 14.0
  #         BRAM_18K: 1867.0
  #         URAM: 392.0
  #         FF: 842758.52
  #         LUT: 639554.64
  #         DSP48E: 2466.0
  #         
  # Total resource consumption: (accelerator kernel without shell)
  # 
  #         HBM_bank: 14.0
  #         BRAM_18K: 1427.0
  #         URAM: 392.0
  #         FF: 518614.52
  #         LUT: 445793.64
  #         DSP48E: 2462.0
  #         
  # 
  # Per Stage Utilization rate (Total = FPGA):
  # Stage 1: {'BRAM_18K': '0.9176587301587302%', 'DSP48E': '0.22163120567375888%', 'FF': '0.10198054737358862%', 'LUT': '0.16507118311242022%', 'URAM': '0.0%'}
  # Stage 2: {'BRAM_18K': '0.0248015873015873%', 'DSP48E': '7.712765957446808%', 'FF': '5.299575049091802%', 'LUT': '8.247882916053019%', 'URAM': '20.0%'}
  # Stage 3: {'BRAM_18K': '0.1488095238095238%', 'DSP48E': '0.0%', 'FF': '0.4053744016936671%', 'LUT': '0.8678502393225331%', 'URAM': '0.0%'}
  # Stage 4: {'BRAM_18K': '8.209325396825397%', 'DSP48E': '5.38563829787234%', 'FF': '3.3516277000490917%', 'LUT': '5.1783413107511045%', 'URAM': '20.833333333333336%'}
  # Stage 5: {'BRAM_18K': '21.875%', 'DSP48E': '13.962765957446807%', 'FF': '9.47326030927835%', 'LUT': '17.62671821305842%', 'URAM': '0.0%'}
  # Stage 6: {'BRAM_18K': '4.216269841269842%', 'DSP48E': '0.0%', 'FF': '1.2585891476435935%', 'LUT': '2.1091563880706925%', 'URAM': '0.0%'}
  # 
  # Per Stage Utilization rate (Total = Accelerator Kernel (without shell)):
  # Stage 1: {'BRAM_18K': '2.592852137351086%', 'DSP48E': '0.8123476848090982%', 'FF': '0.5127122163876168%', 'LUT': '0.48273456750078353%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 1: 0.48273456750078353%
  # Stage 2: {'BRAM_18K': '0.0700770847932726%', 'DSP48E': '28.26969943135662%', 'FF': '26.64387414374746%', 'LUT': '24.120128766305413%', 'URAM': '48.97959183673469%'}
  # LUT only:
  # Stage 2: 24.120128766305413%
  # Stage 3: {'BRAM_18K': '0.42046250875963564%', 'DSP48E': '0.0%', 'FF': '2.038039737105702%', 'LUT': '2.537943340779828%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 3: 2.537943340779828%
  # Stage 4: {'BRAM_18K': '23.19551506657323%', 'DSP48E': '19.740048740861088%', 'FF': '16.85047306427132%', 'LUT': '15.143553864967657%', 'URAM': '51.02040816326531%'}
  # LUT only:
  # Stage 4: 15.143553864967657%
  # Stage 5: {'BRAM_18K': '61.80798878766643%', 'DSP48E': '51.1779041429732%', 'FF': '47.62728201285224%', 'LUT': '51.54761741329463%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 5: 51.54761741329463%
  # Stage 6: {'BRAM_18K': '11.913104414856342%', 'DSP48E': '0.0%', 'FF': '6.327618825635656%', 'LUT': '6.168022047151682%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 6: 6.168022047151682%
  # 
  # Total Utilization rate:
  # {'BRAM_18K': '46.304563492063494%', 'DSP48E': '27.32712765957447%', 'FF': '32.322292280314194%', 'LUT': '49.05763991163476%', 'URAM': '40.833333333333336%'}


  # Constants
  NLIST: 8192
  NPROBE: 17
  D: 128
  M: 16
  K: 256
  TOPK: 1

  QUERY_NUM: 10000

  LARGE_NUM: 99999999 # used to init the heap
  # stage 1
  OPQ_ENABLE: 1
  OPQ_UNROLL_FACTOR: 4 # 4 or 8, the larger the better performance, left None if OPQ_ENABLE=False, only used when OPQ_ENABLE=True

  # stage 2
  # except last PE: compute more distances per query, last one compute less
  # e.g., nlist = 8192, PE num = 15, 
  #   each of the first 14 PEs construct 547 tables (8192 / 15 round up), 
  #   while the last constructs 534: 14 * 547 + 534 = 8192
  STAGE2_ON_CHIP: True
  PE_NUM_CENTER_DIST_COMP: 12

  # stage 3
  STAGE_3_PRIORITY_QUEUE_LEVEL: 2 # support 1 or 2
  STAGE_3_PRIORITY_QUEUE_L1_NUM: 2 # only used when STAGE_3_PRIORITY_QUEUE_LEVEL=2

  # stage 4
  # except last PE: construct more tables per query, last one construct less
  # e.g., nprobe = 17, PE num = 6, each of the first 5 PEs construct 3 tables, 
  #   while the last constructs 2: 5 * 3 + 2 = 17
  PE_NUM_TABLE_CONSTRUCTION: 9

  # stage 5
  # (HBM_CHANNEL_NUM * 3 / STAGE5_COMP_PE_NUM) must be integar
  # e.g., default 1 HBM channel -> 3 PQ code streams -> STAGE5_COMP_PE_NUM = 3 * HBM_CHANNEL_NUM
  # e.g., merge content of 1 HBM channel to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM
  # e.g., merge content of 2 HBM channels to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM / 2
  HBM_CHANNEL_NUM: 14 # PQ code stream num = 3 * HBM_CHANNEL_NUM
  STAGE5_COMP_PE_NUM: 42

  # stage 6
  # there could be a sorting network before the priority queue group (SORT_GROUP_ENABLE)
  #   if not, set SORT_GROUP_ENABLE to False, and SORT_GROUP_NUM to 0 or None
  # number of 16 outputs per cycle, e.g., HBM channel num = 10, comp PE num = 30, then 
  #   SORT_GROUP_NUM = 2; if HBM channel = 12, PE_num = 36, then SORT_GROUP_NUM = 3
  SORT_GROUP_ENABLE: False
  SORT_GROUP_NUM: 0 # only used when SORT_GROUP_ENABLE=True
  STAGE_6_PRIORITY_QUEUE_LEVEL: 2 # supported level num: 2 or 3
  # only fill STAGE_6_PRIORITY_QUEUE_L2_NUM, STAGE_6_STREAM_PER_L2_QUEUE_LARGER, STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  #   when STAGE_6_PRIORITY_QUEUE_LEVEL = 3, else left them blank
  # Must subject to: L1 stream num = (without sort-reduction unit) STAGE5_COMP_PE_NUM * 2 
  #                  or = (with sort reduction) 16 * 2
  # (STAGE_6_PRIORITY_QUEUE_L2_NUM - 1) * STAGE_6_STREAM_PER_L2_QUEUE_LARGER + STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: 2 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: 6 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: 4 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3

  # Dataset config
  DB_SCALE: 100M # 1M to 1000M
  FPGA_NUM: 1 # e.g., can use 8 FPGAs to serve 1000M dataset, each stores 125M vectors

  # Data directory (don't add "/" after the dir)
  #   e.g., dir=/home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks, 
  #     then the content for HBM0 is:
  #     /home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks/HBM_bank_0_raw
  # DATA_DIR: "/mnt/scratch/wenqi/saved_npy_data/FPGA_data_SIFT100M_IVF4096,PQ16_23_banks"
  # GT_DIR: "/mnt/scratch/wenqi/saved_npy_data/gnd/"

  # FPGA Settings
  DEVICE: U280 # Supported devices: U280, U250, U50
  FREQ: 140
