---

    # 
  # 
  # ======== Result =========
  # 
  # best option name nlist_32768_nprobe_16_OPQ_1
  # nprobe: 16
  # QPS 4254.5432443931195
  # stage_option_list
  # Stage 1:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 37
  #         URAM: 0
  #         FF: 2659
  #         LUT: 2152
  #         DSP48E: 20
  #         
  # QPS: 32014.635261833984
  # Cycles per query: 4373.0
  # OPQ_ENABLE: True
  # OPQ_UNROLL_FACTOR: 4
  # Stage 2:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 1.0
  #         URAM: 512.0
  #         FF: 184199
  #         LUT: 143310
  #         DSP48E: 928
  #         
  # QPS: 4254.5432443931195
  # Cycles per query: 32906
  # STAGE2_ON_CHIP: True
  # STAGE2_OFF_CHIP_START_CHANNEL:None
  # PE_NUM_CENTER_DIST_COMP: 16
  # Stage 3:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 6.0
  #         URAM: 0
  #         FF: 9981.36
  #         LUT: 10667.52
  #         DSP48E: 0
  #         
  # QPS: 4269.073611026407
  # Cycles per query: 32794
  # STAGE_3_PRIORITY_QUEUE_LEVEL: 2
  # STAGE_3_PRIORITY_QUEUE_L1_NUM: 2
  # Stage 4:
  # 
  #         HBM_bank: 1
  #         BRAM_18K: 217.0
  #         URAM: 24
  #         FF: 39263
  #         LUT: 28263
  #         DSP48E: 162
  #         
  # QPS: 5444.928438083385
  # Cycles per query: 25712
  # PE_NUM_TABLE_CONSTRUCTION: 3
  # Stage 5:
  # 
  #         HBM_bank: 9.0
  #         BRAM_18K: 63.0
  #         URAM: 0.0
  #         FF: 17643.0
  #         LUT: 16414.0
  #         DSP48E: 90.0
  #         
  # QPS: 5884.3308675184935
  # Cycles per query: 23792
  # HBM_CHANNEL_NUM: 9
  # STAGE5_COMP_PE_NUM: 3
  # Stage 6:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 14.0
  #         URAM: 0
  #         FF: 15054.899999999998
  #         LUT: 15840.300000000001
  #         DSP48E: 0
  #         
  # QPS: 7509.118214975327
  # Cycles per query: 18644
  # 
  # SORT_GROUP_ENABLE: False
  # SORT_GROUP_NUM: None
  # STAGE_6_PRIORITY_QUEUE_LEVEL: 2
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: None
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: None
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: None
  #         
  # total_valid_design: 328797
  # Total resource consumption: (with shell)
  # 
  #         HBM_bank: 10.0
  #         BRAM_18K: 778.0
  #         URAM: 536.0
  #         FF: 592944.26
  #         LUT: 410407.81999999995
  #         DSP48E: 1204.0
  #         
  # Total resource consumption: (accelerator kernel without shell)
  # 
  #         HBM_bank: 10.0
  #         BRAM_18K: 338.0
  #         URAM: 536.0
  #         FF: 268800.26
  #         LUT: 216646.81999999998
  #         DSP48E: 1200.0
  #         
  # 
  # Per Stage Utilization rate (Total = FPGA):
  # Stage 1: {'BRAM_18K': '0.9176587301587302%', 'DSP48E': '0.22163120567375888%', 'FF': '0.10198054737358862%', 'LUT': '0.16507118311242022%', 'URAM': '0.0%'}
  # Stage 2: {'BRAM_18K': '0.0248015873015873%', 'DSP48E': '10.28368794326241%', 'FF': '7.064578730976927%', 'LUT': '10.992728276877761%', 'URAM': '53.333333333333336%'}
  # Stage 3: {'BRAM_18K': '0.1488095238095238%', 'DSP48E': '0.0%', 'FF': '0.38281480117820327%', 'LUT': '0.8182621502209131%', 'URAM': '0.0%'}
  # Stage 4: {'BRAM_18K': '5.381944444444445%', 'DSP48E': '1.795212765957447%', 'FF': '1.5058526632302405%', 'LUT': '2.1679399852724592%', 'URAM': '2.5%'}
  # Stage 5: {'BRAM_18K': '1.5625%', 'DSP48E': '0.9973404255319149%', 'FF': '0.6766614506627393%', 'LUT': '1.2590513009327442%', 'URAM': '0.0%'}
  # Stage 6: {'BRAM_18K': '0.3472222222222222%', 'DSP48E': '0.0%', 'FF': '0.5774001288659794%', 'LUT': '1.2150451030927836%', 'URAM': '0.0%'}
  # 
  # Per Stage Utilization rate (Total = Accelerator Kernel (without shell)):
  # Stage 1: {'BRAM_18K': '10.946745562130179%', 'DSP48E': '1.6666666666666667%', 'FF': '0.9892103526983196%', 'LUT': '0.9933217575037567%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 1: 0.9933217575037567%
  # Stage 2: {'BRAM_18K': '0.2958579881656805%', 'DSP48E': '77.33333333333333%', 'FF': '68.52634740755087%', 'LUT': '66.14913618395138%', 'URAM': '95.52238805970148%'}
  # LUT only:
  # Stage 2: 66.14913618395138%
  # Stage 3: {'BRAM_18K': '1.7751479289940828%', 'DSP48E': '0.0%', 'FF': '3.7132999796949604%', 'LUT': '4.923921800467693%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 3: 4.923921800467693%
  # Stage 4: {'BRAM_18K': '64.20118343195266%', 'DSP48E': '13.5%', 'FF': '14.606756704774021%', 'LUT': '13.045656520598827%', 'URAM': '4.477611940298507%'}
  # LUT only:
  # Stage 4: 13.045656520598827%
  # Stage 5: {'BRAM_18K': '18.639053254437872%', 'DSP48E': '7.5%', 'FF': '6.56360972269893%', 'LUT': '7.576386304677817%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 5: 7.576386304677817%
  # Stage 6: {'BRAM_18K': '4.142011834319527%', 'DSP48E': '0.0%', 'FF': '5.600775832582899%', 'LUT': '7.311577432800538%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 6: 7.311577432800538%
  # 
  # Total Utilization rate:
  # {'BRAM_18K': '19.29563492063492%', 'DSP48E': '13.342198581560282%', 'FF': '22.74117344747177%', 'LUT': '31.480717660775646%', 'URAM': '55.833333333333336%'}


  # Constants
  NLIST: 32768
  NPROBE: 16
  D: 128
  M: 16
  K: 256
  TOPK: 10

  QUERY_NUM: 10000

  LARGE_NUM: 99999999 # used to init the heap
  # stage 1
  OPQ_ENABLE: 1
  OPQ_UNROLL_FACTOR: 4 # 4 or 8, the larger the better performance, left None if OPQ_ENABLE=False, only used when OPQ_ENABLE=True

  # stage 2
  # except last PE: compute more distances per query, last one compute less
  # e.g., nlist = 8192, PE num = 15, 
  #   each of the first 14 PEs construct 547 tables (8192 / 15 round up), 
  #   while the last constructs 534: 14 * 547 + 534 = 8192
  STAGE2_ON_CHIP: True
  PE_NUM_CENTER_DIST_COMP: 16

  # stage 3
  STAGE_3_PRIORITY_QUEUE_LEVEL: 2 # support 1 or 2
  STAGE_3_PRIORITY_QUEUE_L1_NUM: 2 # only used when STAGE_3_PRIORITY_QUEUE_LEVEL=2

  # stage 4
  # except last PE: construct more tables per query, last one construct less
  # e.g., nprobe = 17, PE num = 6, each of the first 5 PEs construct 3 tables, 
  #   while the last constructs 2: 5 * 3 + 2 = 17
  PE_NUM_TABLE_CONSTRUCTION: 3

  # stage 5
  # (HBM_CHANNEL_NUM * 3 / STAGE5_COMP_PE_NUM) must be integar
  # e.g., default 1 HBM channel -> 3 PQ code streams -> STAGE5_COMP_PE_NUM = 3 * HBM_CHANNEL_NUM
  # e.g., merge content of 1 HBM channel to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM
  # e.g., merge content of 2 HBM channels to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM / 2
  HBM_CHANNEL_NUM: 9 # PQ code stream num = 3 * HBM_CHANNEL_NUM
  STAGE5_COMP_PE_NUM: 3

  # stage 6
  # there could be a sorting network before the priority queue group (SORT_GROUP_ENABLE)
  #   if not, set SORT_GROUP_ENABLE to False, and SORT_GROUP_NUM to 0 or None
  # number of 16 outputs per cycle, e.g., HBM channel num = 10, comp PE num = 30, then 
  #   SORT_GROUP_NUM = 2; if HBM channel = 12, PE_num = 36, then SORT_GROUP_NUM = 3
  SORT_GROUP_ENABLE: False
  SORT_GROUP_NUM: 0 # only used when SORT_GROUP_ENABLE=True
  STAGE_6_PRIORITY_QUEUE_LEVEL: 2 # supported level num: 2 or 3
  # only fill STAGE_6_PRIORITY_QUEUE_L2_NUM, STAGE_6_STREAM_PER_L2_QUEUE_LARGER, STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  #   when STAGE_6_PRIORITY_QUEUE_LEVEL = 3, else left them blank
  # Must subject to: L1 stream num = (without sort-reduction unit) STAGE5_COMP_PE_NUM * 2 
  #                  or = (with sort reduction) 16 * 2
  # (STAGE_6_PRIORITY_QUEUE_L2_NUM - 1) * STAGE_6_STREAM_PER_L2_QUEUE_LARGER + STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: 2 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: 6 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: 4 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3

  # Dataset config
  DB_SCALE: 100M # 1M to 1000M
  FPGA_NUM: 1 # e.g., can use 8 FPGAs to serve 1000M dataset, each stores 125M vectors

  # Data directory (don't add "/" after the dir)
  #   e.g., dir=/home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks, 
  #     then the content for HBM0 is:
  #     /home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks/HBM_bank_0_raw
  # DATA_DIR: "/mnt/scratch/wenqi/saved_npy_data/FPGA_data_SIFT100M_IVF4096,PQ16_23_banks"
  # GT_DIR: "/mnt/scratch/wenqi/saved_npy_data/gnd/"

  # FPGA Settings
  DEVICE: U280 # Supported devices: U280, U250, U50
  FREQ: 140
