---

    # 
  # 
  # ======== Result =========
  # 
  # best option name nlist_8192_nprobe_17_OPQ_1
  # nprobe: 17
  # QPS 4403.900597672224
  # stage_option_list
  # Stage 1:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 37
  #         URAM: 0
  #         FF: 2659
  #         LUT: 2152
  #         DSP48E: 20
  #         
  # QPS: 32014.635261833984
  # Cycles per query: 4373.0
  # OPQ_ENABLE: True
  # OPQ_UNROLL_FACTOR: 4
  # Stage 2:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 1.0
  #         URAM: 160.0
  #         FF: 57644
  #         LUT: 44904
  #         DSP48E: 290
  #         
  # QPS: 5312.286559915004
  # Cycles per query: 26354
  # STAGE2_ON_CHIP: True
  # STAGE2_OFF_CHIP_START_CHANNEL:None
  # PE_NUM_CENTER_DIST_COMP: 5
  # Stage 3:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 1.0
  #         URAM: 0
  #         FF: 3428.19
  #         LUT: 3717.33
  #         DSP48E: 0
  #         
  # QPS: 8530.863445250137
  # Cycles per query: 16411
  # STAGE_3_PRIORITY_QUEUE_LEVEL: 1
  # STAGE_3_PRIORITY_QUEUE_L1_NUM: 1
  # Stage 4:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 217.0
  #         URAM: 152
  #         FF: 39263
  #         LUT: 28263
  #         DSP48E: 162
  #         
  # QPS: 5444.928438083385
  # Cycles per query: 25712
  # PE_NUM_TABLE_CONSTRUCTION: 3
  # Stage 5:
  # 
  #         HBM_bank: 9.0
  #         BRAM_18K: 189.0
  #         URAM: 0.0
  #         FF: 52929.0
  #         LUT: 49242.0
  #         DSP48E: 270.0
  #         
  # QPS: 4403.900597672224
  # Cycles per query: 31790
  # HBM_CHANNEL_NUM: 9
  # STAGE5_COMP_PE_NUM: 9
  # Stage 6:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 38.0
  #         URAM: 0
  #         FF: 376143.0
  #         LUT: 411483.0
  #         DSP48E: 0
  #         
  # QPS: 5321.97977647685
  # Cycles per query: 26306
  # 
  # SORT_GROUP_ENABLE: False
  # SORT_GROUP_NUM: None
  # STAGE_6_PRIORITY_QUEUE_LEVEL: 2
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: None
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: None
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: None
  #         
  # total_valid_design: 323511
  # Total resource consumption: (with shell)
  # 
  #         HBM_bank: 9.0
  #         BRAM_18K: 923.0
  #         URAM: 312.0
  #         FF: 856210.19
  #         LUT: 733522.33
  #         DSP48E: 746.0
  #         
  # Total resource consumption: (accelerator kernel without shell)
  # 
  #         HBM_bank: 9.0
  #         BRAM_18K: 483.0
  #         URAM: 312.0
  #         FF: 532066.19
  #         LUT: 539761.33
  #         DSP48E: 742.0
  #         
  # 
  # Per Stage Utilization rate (Total = FPGA):
  # Stage 1: {'BRAM_18K': '0.9176587301587302%', 'DSP48E': '0.22163120567375888%', 'FF': '0.10198054737358862%', 'LUT': '0.16507118311242022%', 'URAM': '0.0%'}
  # Stage 2: {'BRAM_18K': '0.0248015873015873%', 'DSP48E': '3.2136524822695036%', 'FF': '2.2108186057928325%', 'LUT': '3.4444035346097204%', 'URAM': '16.666666666666664%'}
  # Stage 3: {'BRAM_18K': '0.0248015873015873%', 'DSP48E': '0.0%', 'FF': '0.13148126840942564%', 'LUT': '0.28514129234167895%', 'URAM': '0.0%'}
  # Stage 4: {'BRAM_18K': '5.381944444444445%', 'DSP48E': '1.795212765957447%', 'FF': '1.5058526632302405%', 'LUT': '2.1679399852724592%', 'URAM': '15.833333333333332%'}
  # Stage 5: {'BRAM_18K': '4.6875%', 'DSP48E': '2.992021276595745%', 'FF': '2.029984351988218%', 'LUT': '3.7771539027982324%', 'URAM': '0.0%'}
  # Stage 6: {'BRAM_18K': '0.9424603174603174%', 'DSP48E': '0.0%', 'FF': '14.426201215022092%', 'LUT': '31.563190353460975%', 'URAM': '0.0%'}
  # 
  # Per Stage Utilization rate (Total = Accelerator Kernel (without shell)):
  # Stage 1: {'BRAM_18K': '7.6604554865424435%', 'DSP48E': '2.6954177897574128%', 'FF': '0.49974985255123994%', 'LUT': '0.3986947342078026%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 1: 0.3986947342078026%
  # Stage 2: {'BRAM_18K': '0.2070393374741201%', 'DSP48E': '39.083557951482476%', 'FF': '10.833990410102924%', 'LUT': '8.319232502261695%', 'URAM': '51.28205128205128%'}
  # LUT only:
  # Stage 2: 8.319232502261695%
  # Stage 3: {'BRAM_18K': '0.2070393374741201%', 'DSP48E': '0.0%', 'FF': '0.6443164524323564%', 'LUT': '0.6886988365765292%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 3: 0.6886988365765292%
  # Stage 4: {'BRAM_18K': '44.927536231884055%', 'DSP48E': '21.83288409703504%', 'FF': '7.379345039759058%', 'LUT': '5.236203193733794%', 'URAM': '48.717948717948715%'}
  # LUT only:
  # Stage 4: 5.236203193733794%
  # Stage 5: {'BRAM_18K': '39.130434782608695%', 'DSP48E': '36.38814016172507%', 'FF': '9.947822469230756%', 'LUT': '9.122921051050472%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 5: 9.122921051050472%
  # Stage 6: {'BRAM_18K': '7.867494824016563%', 'DSP48E': '0.0%', 'FF': '70.69477577592367%', 'LUT': '76.23424968216972%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 6: 76.23424968216972%
  # 
  # Total Utilization rate:
  # {'BRAM_18K': '22.89186507936508%', 'DSP48E': '8.266843971631205%', 'FF': '32.838203777000494%', 'LUT': '56.26551991286205%', 'URAM': '32.5%'}


  # Constants
  NLIST: 8192
  NPROBE: 17
  D: 128
  M: 16
  K: 256
  TOPK: 100

  QUERY_NUM: 10000

  LARGE_NUM: 99999999 # used to init the heap
  # stage 1
  OPQ_ENABLE: 1
  OPQ_UNROLL_FACTOR: 4 # 4 or 8, the larger the better performance, left None if OPQ_ENABLE=False, only used when OPQ_ENABLE=True

  # stage 2
  # except last PE: compute more distances per query, last one compute less
  # e.g., nlist = 8192, PE num = 15, 
  #   each of the first 14 PEs construct 547 tables (8192 / 15 round up), 
  #   while the last constructs 534: 14 * 547 + 534 = 8192
  STAGE2_ON_CHIP: True
  PE_NUM_CENTER_DIST_COMP: 5

  # stage 3
  STAGE_3_PRIORITY_QUEUE_LEVEL: 1 # support 1 or 2
  STAGE_3_PRIORITY_QUEUE_L1_NUM: 1 # only used when STAGE_3_PRIORITY_QUEUE_LEVEL=2

  # stage 4
  # except last PE: construct more tables per query, last one construct less
  # e.g., nprobe = 17, PE num = 6, each of the first 5 PEs construct 3 tables, 
  #   while the last constructs 2: 5 * 3 + 2 = 17
  PE_NUM_TABLE_CONSTRUCTION: 3

  # stage 5
  # (HBM_CHANNEL_NUM * 3 / STAGE5_COMP_PE_NUM) must be integar
  # e.g., default 1 HBM channel -> 3 PQ code streams -> STAGE5_COMP_PE_NUM = 3 * HBM_CHANNEL_NUM
  # e.g., merge content of 1 HBM channel to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM
  # e.g., merge content of 2 HBM channels to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM / 2
  HBM_CHANNEL_NUM: 9 # PQ code stream num = 3 * HBM_CHANNEL_NUM
  STAGE5_COMP_PE_NUM: 9

  # stage 6
  # there could be a sorting network before the priority queue group (SORT_GROUP_ENABLE)
  #   if not, set SORT_GROUP_ENABLE to False, and SORT_GROUP_NUM to 0 or None
  # number of 16 outputs per cycle, e.g., HBM channel num = 10, comp PE num = 30, then 
  #   SORT_GROUP_NUM = 2; if HBM channel = 12, PE_num = 36, then SORT_GROUP_NUM = 3
  SORT_GROUP_ENABLE: False
  SORT_GROUP_NUM: 0 # only used when SORT_GROUP_ENABLE=True
  STAGE_6_PRIORITY_QUEUE_LEVEL: 2 # supported level num: 2 or 3
  # only fill STAGE_6_PRIORITY_QUEUE_L2_NUM, STAGE_6_STREAM_PER_L2_QUEUE_LARGER, STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  #   when STAGE_6_PRIORITY_QUEUE_LEVEL = 3, else left them blank
  # Must subject to: L1 stream num = (without sort-reduction unit) STAGE5_COMP_PE_NUM * 2 
  #                  or = (with sort reduction) 16 * 2
  # (STAGE_6_PRIORITY_QUEUE_L2_NUM - 1) * STAGE_6_STREAM_PER_L2_QUEUE_LARGER + STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: 2 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: 6 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: 4 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3

  # Dataset config
  DB_SCALE: 100M # 1M to 1000M
  FPGA_NUM: 1 # e.g., can use 8 FPGAs to serve 1000M dataset, each stores 125M vectors

  # Data directory (don't add "/" after the dir)
  #   e.g., dir=/home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks, 
  #     then the content for HBM0 is:
  #     /home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks/HBM_bank_0_raw
  # DATA_DIR: "/mnt/scratch/wenqi/saved_npy_data/FPGA_data_SIFT100M_IVF4096,PQ16_23_banks"
  # GT_DIR: "/mnt/scratch/wenqi/saved_npy_data/gnd/"

  # FPGA Settings
  DEVICE: U280 # Supported devices: U280, U250, U50
  FREQ: 140
