---

    # 
  # 
  # ======== Result =========
  # 
  # best option name IVF1024,PQ16
  # nprobe: 2
  # QPS 31876.138433515483
  # stage_option_list
  # Stage 2:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 1.0
  #         URAM: 32.0
  #         FF: 46139
  #         LUT: 35958
  #         DSP48E: 232
  #         
  # QPS: 33065.658951346246
  # Cycles per query: 4234
  # STAGE2_ON_CHIP: True
  # STAGE2_OFF_CHIP_START_CHANNEL:None
  # PE_NUM_CENTER_DIST_COMP: 4
  # Stage 3:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 1.0
  #         URAM: 0
  #         FF: 487.14
  #         LUT: 484.98
  #         DSP48E: 0
  #         
  # QPS: 67961.16504854368
  # Cycles per query: 2060
  # STAGE_3_PRIORITY_QUEUE_LEVEL: 1
  # STAGE_3_PRIORITY_QUEUE_L1_NUM: 1
  # Stage 4:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 54.0
  #         URAM: 32
  #         FF: 17562
  #         LUT: 13946
  #         DSP48E: 108
  #         
  # QPS: 31876.138433515483
  # Cycles per query: 4392
  # PE_NUM_TABLE_CONSTRUCTION: 2
  # Stage 5:
  # 
  #         HBM_bank: 25.0
  #         BRAM_18K: 1575.0
  #         URAM: 0.0
  #         FF: 441075.0
  #         LUT: 410350.0
  #         DSP48E: 2250.0
  #         
  # QPS: 31963.470319634704
  # Cycles per query: 4380
  # HBM_CHANNEL_NUM: 25
  # STAGE5_COMP_PE_NUM: 75
  # Stage 6:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 302.0
  #         URAM: 0
  #         FF: 58296.57
  #         LUT: 48846.990000000005
  #         DSP48E: 0
  #         
  # QPS: 38878.08941960566
  # Cycles per query: 3601
  # 
  # SORT_GROUP_ENABLE: False
  # SORT_GROUP_NUM: None
  # STAGE_6_PRIORITY_QUEUE_LEVEL: 2
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: None
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: None
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: None
  #         
  # total_valid_design: 19677708
  # Total resource consumption: (with shell)
  # 
  #         HBM_bank: 25.0
  #         BRAM_18K: 2373.0
  #         URAM: 64.0
  #         FF: 887703.71
  #         LUT: 703346.97
  #         DSP48E: 2594.0
  #         
  # Total resource consumption: (accelerator kernel without shell)
  # 
  #         HBM_bank: 25.0
  #         BRAM_18K: 1933.0
  #         URAM: 64.0
  #         FF: 563559.71
  #         LUT: 509585.97
  #         DSP48E: 2590.0
  #         
  # Per Stage Utilization rate (Total = FPGA):
  # 
  # Stage 2: {'BRAM_18K': '0.0248015873015873%', 'DSP48E': '2.5709219858156027%', 'FF': '1.7695676853215512%', 'LUT': '2.7581921944035344%', 'URAM': '3.3333333333333335%'}
  # Stage 3: {'BRAM_18K': '0.0248015873015873%', 'DSP48E': '0.0%', 'FF': '0.018683265832106038%', 'LUT': '0.0372008468335788%', 'URAM': '0.0%'}
  # Stage 4: {'BRAM_18K': '1.3392857142857142%', 'DSP48E': '1.196808510638298%', 'FF': '0.6735548600883653%', 'LUT': '1.0697410407461954%', 'URAM': '3.3333333333333335%'}
  # Stage 5: {'BRAM_18K': '39.0625%', 'DSP48E': '24.933510638297875%', 'FF': '16.91653626656848%', 'LUT': '31.476282523318606%', 'URAM': '0.0%'}
  # Stage 6: {'BRAM_18K': '7.490079365079365%', 'DSP48E': '0.0%', 'FF': '2.2358466034609723%', 'LUT': '3.746854289396171%', 'URAM': '0.0%'}
  # Per Stage Utilization rate (Total = Accelerator Kernel (without shell)):
  # 
  # Stage 2: {'BRAM_18K': '0.05173305742369374%', 'DSP48E': '8.957528957528957%', 'FF': '8.187065040543796%', 'LUT': '7.056316719237776%', 'URAM': '50.0%'}
  # Stage 3: {'BRAM_18K': '0.05173305742369374%', 'DSP48E': '0.0%', 'FF': '0.08643982019225611%', 'LUT': '0.09517138001267972%', 'URAM': '0.0%'}
  # Stage 4: {'BRAM_18K': '2.793585100879462%', 'DSP48E': '4.16988416988417%', 'FF': '3.1162625163534137%', 'LUT': '2.736731546985095%', 'URAM': '50.0%'}
  # Stage 5: {'BRAM_18K': '81.47956544231764%', 'DSP48E': '86.87258687258688%', 'FF': '78.26588596974045%', 'LUT': '80.52615734298965%', 'URAM': '0.0%'}
  # Stage 6: {'BRAM_18K': '15.62338334195551%', 'DSP48E': '0.0%', 'FF': '10.34434665317008%', 'LUT': '9.585623010774807%', 'URAM': '0.0%'}
  # Total Utilization rate:
  # {'BRAM_18K': '58.854166666666664%', 'DSP48E': '28.745567375886527%', 'FF': '34.04607380645557%', 'LUT': '53.95089055596465%', 'URAM': '6.666666666666667%'}


  # Constants
  NLIST: 1024
  NPROBE: 2
  D: 128
  M: 16
  K: 256
  TOPK: 1

  QUERY_NUM: 10000

  LARGE_NUM: 99999999 # used to init the heap
  # stage 1
  OPQ_ENABLE: False
  OPQ_UNROLL_FACTOR: <--OPQ_unroll_factor--> # 4 or 8, the larger the better performance, left None if OPQ_ENABLE=False, only used when OPQ_ENABLE=True

  # stage 2
  # except last PE: compute more distances per query, last one compute less
  # e.g., nlist = 8192, PE num = 15, 
  #   each of the first 14 PEs construct 547 tables (8192 / 15 round up), 
  #   while the last constructs 534: 14 * 547 + 534 = 8192
  STAGE2_ON_CHIP: True
  PE_NUM_CENTER_DIST_COMP: 4

  # stage 3
  STAGE_3_PRIORITY_QUEUE_LEVEL: 1 # support 1 or 2
  STAGE_3_PRIORITY_QUEUE_L1_NUM: 1 # only used when STAGE_3_PRIORITY_QUEUE_LEVEL=2

  # stage 4
  # except last PE: construct more tables per query, last one construct less
  # e.g., nprobe = 17, PE num = 6, each of the first 5 PEs construct 3 tables, 
  #   while the last constructs 2: 5 * 3 + 2 = 17
  PE_NUM_TABLE_CONSTRUCTION: 2

  # stage 5
  # (HBM_CHANNEL_NUM * 3 / STAGE5_COMP_PE_NUM) must be integar
  # e.g., default 1 HBM channel -> 3 PQ code streams -> STAGE5_COMP_PE_NUM = 3 * HBM_CHANNEL_NUM
  # e.g., merge content of 1 HBM channel to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM
  # e.g., merge content of 2 HBM channels to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM / 2
  HBM_CHANNEL_NUM: 25 # PQ code stream num = 3 * HBM_CHANNEL_NUM
  STAGE5_COMP_PE_NUM: 75

  # stage 6
  # there could be a sorting network before the priority queue group (SORT_GROUP_ENABLE)
  #   if not, set SORT_GROUP_ENABLE to False, and SORT_GROUP_NUM to 0 or None
  # number of 16 outputs per cycle, e.g., HBM channel num = 10, comp PE num = 30, then 
  #   SORT_GROUP_NUM = 2; if HBM channel = 12, PE_num = 36, then SORT_GROUP_NUM = 3
  SORT_GROUP_ENABLE: False
  SORT_GROUP_NUM: 0 # only used when SORT_GROUP_ENABLE=True
  STAGE_6_PRIORITY_QUEUE_LEVEL: 2 # supported level num: 2 or 3
  # only fill STAGE_6_PRIORITY_QUEUE_L2_NUM, STAGE_6_STREAM_PER_L2_QUEUE_LARGER, STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  #   when STAGE_6_PRIORITY_QUEUE_LEVEL = 3, else left them blank
  # Must subject to: L1 stream num = (without sort-reduction unit) STAGE5_COMP_PE_NUM * 2 
  #                  or = (with sort reduction) 16 * 2
  # (STAGE_6_PRIORITY_QUEUE_L2_NUM - 1) * STAGE_6_STREAM_PER_L2_QUEUE_LARGER + STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: 2 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: 6 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: 4 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3

  # Dataset config
  DB_SCALE: 500M # 1M to 1000M
  FPGA_NUM: 4 # e.g., can use 8 FPGAs to serve 1000M dataset, each stores 125M vectors

  # Data directory (don't add "/" after the dir)
  #   e.g., dir=/home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks, 
  #     then the content for HBM0 is:
  #     /home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks/HBM_bank_0_raw
  # DATA_DIR: "/mnt/scratch/wenqi/saved_npy_data/FPGA_data_SIFT100M_IVF4096,PQ16_23_banks"
  # GT_DIR: "/mnt/scratch/wenqi/saved_npy_data/gnd/"

  # FPGA Settings
  DEVICE: U280 # Supported devices: U280, U250, U50
  FREQ: 140
