---

    # 
  # 
  # ======== Result =========
  # 
  # best option name OPQ16,IVF8192,PQ16
  # nprobe: 17
  # QPS 5534.471853257432
  # stage_option_list
  # Stage 1:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 37
  #         URAM: 0
  #         FF: 2659
  #         LUT: 2152
  #         DSP48E: 20
  #         
  # QPS: 32014.635261833984
  # Cycles per query: 4373.0
  # OPQ_ENABLE: True
  # OPQ_UNROLL_FACTOR: 4
  # Stage 2:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 1.0
  #         URAM: 144.0
  #         FF: 69149
  #         LUT: 53850
  #         DSP48E: 348
  #         
  # QPS: 6368.267831149928
  # Cycles per query: 21984
  # STAGE2_ON_CHIP: True
  # STAGE2_OFF_CHIP_START_CHANNEL:None
  # PE_NUM_CENTER_DIST_COMP: 6
  # Stage 3:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 1.0
  #         URAM: 0
  #         FF: 3428.19
  #         LUT: 3717.33
  #         DSP48E: 0
  #         
  # QPS: 8530.863445250137
  # Cycles per query: 16411
  # STAGE_3_PRIORITY_QUEUE_LEVEL: 1
  # STAGE_3_PRIORITY_QUEUE_L1_NUM: 1
  # Stage 4:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 220.0
  #         URAM: 160
  #         FF: 45764
  #         LUT: 33940
  #         DSP48E: 216
  #         
  # QPS: 6527.4151436031325
  # Cycles per query: 21448
  # PE_NUM_TABLE_CONSTRUCTION: 4
  # Stage 5:
  # 
  #         HBM_bank: 4.0
  #         BRAM_18K: 252.0
  #         URAM: 0.0
  #         FF: 70572.0
  #         LUT: 65656.0
  #         DSP48E: 360.0
  #         
  # QPS: 5534.471853257432
  # Cycles per query: 25296
  # HBM_CHANNEL_NUM: 4
  # STAGE5_COMP_PE_NUM: 12
  # Stage 6:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 50.0
  #         URAM: 0
  #         FF: 53767.49999999999
  #         LUT: 56572.5
  #         DSP48E: 0
  #         
  # QPS: 7116.71411142741
  # Cycles per query: 19672
  # 
  # SORT_GROUP_ENABLE: False
  # SORT_GROUP_NUM: None
  # STAGE_6_PRIORITY_QUEUE_LEVEL: 2
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: None
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: None
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: None
  #         
  # total_valid_design: 441471
  # Total resource consumption: (with shell)
  # 
  #         HBM_bank: 4.0
  #         BRAM_18K: 1645.0
  #         URAM: 304.0
  #         FF: 626117.69
  #         LUT: 465031.83
  #         DSP48E: 960.0
  #         
  # Total resource consumption: (accelerator kernel without shell)
  # 
  #         HBM_bank: 4.0
  #         BRAM_18K: 561.0
  #         URAM: 304.0
  #         FF: 245339.69
  #         LUT: 215887.83000000002
  #         DSP48E: 944.0
  #         
  # 
  # Per Stage Utilization rate (Total = FPGA):
  # Stage 1: {'BRAM_18K': '0.6882440476190476%', 'DSP48E': '0.16276041666666669%', 'FF': '0.07693865740740741%', 'LUT': '0.12453703703703704%', 'URAM': '0.0%'}
  # Stage 2: {'BRAM_18K': '0.018601190476190476%', 'DSP48E': '2.83203125%', 'FF': '2.00083912037037%', 'LUT': '3.1163194444444446%', 'URAM': '11.25%'}
  # Stage 3: {'BRAM_18K': '0.018601190476190476%', 'DSP48E': '0.0%', 'FF': '0.0991953125%', 'LUT': '0.21512326388888886%', 'URAM': '0.0%'}
  # Stage 4: {'BRAM_18K': '4.092261904761905%', 'DSP48E': '1.7578125%', 'FF': '1.3241898148148148%', 'LUT': '1.9641203703703702%', 'URAM': '12.5%'}
  # Stage 5: {'BRAM_18K': '4.6875%', 'DSP48E': '2.9296875%', 'FF': '2.042013888888889%', 'LUT': '3.7995370370370374%', 'URAM': '0.0%'}
  # Stage 6: {'BRAM_18K': '0.9300595238095238%', 'DSP48E': '0.0%', 'FF': '1.5557725694444442%', 'LUT': '3.2738715277777777%', 'URAM': '0.0%'}
  # 
  # Per Stage Utilization rate (Total = Accelerator Kernel (without shell)):
  # Stage 1: {'BRAM_18K': '6.59536541889483%', 'DSP48E': '2.11864406779661%', 'FF': '1.083803440038585%', 'LUT': '0.9968139473169931%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 1: 0.9968139473169931%
  # Stage 2: {'BRAM_18K': '0.17825311942959002%', 'DSP48E': '36.86440677966102%', 'FF': '28.18500341302298%', 'LUT': '24.94350885828071%', 'URAM': '47.368421052631575%'}
  # LUT only:
  # Stage 2: 24.94350885828071%
  # Stage 3: {'BRAM_18K': '0.17825311942959002%', 'DSP48E': '0.0%', 'FF': '1.3973238492312434%', 'LUT': '1.7218802931133264%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 3: 1.7218802931133264%
  # Stage 4: {'BRAM_18K': '39.21568627450981%', 'DSP48E': '22.88135593220339%', 'FF': '18.653321034195486%', 'LUT': '15.72112703157005%', 'URAM': '52.63157894736842%'}
  # LUT only:
  # Stage 4: 15.72112703157005%
  # Stage 5: {'BRAM_18K': '44.919786096256686%', 'DSP48E': '38.13559322033898%', 'FF': '28.765015558632197%', 'LUT': '30.412089463310643%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 5: 30.412089463310643%
  # Stage 6: {'BRAM_18K': '8.9126559714795%', 'DSP48E': '0.0%', 'FF': '21.915532704879507%', 'LUT': '26.20458040640827%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 6: 26.20458040640827%
  # 
  # Total Utilization rate:
  # {'BRAM_18K': '30.598958333333332%', 'DSP48E': '7.8125%', 'FF': '18.116831307870367%', 'LUT': '26.91156423611111%', 'URAM': '23.75%'}


  # Constants
  NLIST: 8192
  NPROBE: 17
  D: 128
  M: 16
  K: 256
  TOPK: 10

  QUERY_NUM: 10000

  LARGE_NUM: 99999999 # used to init the heap
  # stage 1
  OPQ_ENABLE: True
  OPQ_UNROLL_FACTOR: 4 # 4 or 8, the larger the better performance, left None if OPQ_ENABLE=False, only used when OPQ_ENABLE=True

  # stage 2
  # except last PE: compute more distances per query, last one compute less
  # e.g., nlist = 8192, PE num = 15, 
  #   each of the first 14 PEs construct 547 tables (8192 / 15 round up), 
  #   while the last constructs 534: 14 * 547 + 534 = 8192
  STAGE2_ON_CHIP: True
  PE_NUM_CENTER_DIST_COMP: 6

  # stage 3
  STAGE_3_PRIORITY_QUEUE_LEVEL: 1 # support 1 or 2
  STAGE_3_PRIORITY_QUEUE_L1_NUM: 1 # only used when STAGE_3_PRIORITY_QUEUE_LEVEL=2

  # stage 4
  # except last PE: construct more tables per query, last one construct less
  # e.g., nprobe = 17, PE num = 6, each of the first 5 PEs construct 3 tables, 
  #   while the last constructs 2: 5 * 3 + 2 = 17
  PE_NUM_TABLE_CONSTRUCTION: 4

  # stage 5
  # (HBM_CHANNEL_NUM * 3 / STAGE5_COMP_PE_NUM) must be integar
  # e.g., default 1 HBM channel -> 3 PQ code streams -> STAGE5_COMP_PE_NUM = 3 * HBM_CHANNEL_NUM
  # e.g., merge content of 1 HBM channel to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM
  # e.g., merge content of 2 HBM channels to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM / 2
  HBM_CHANNEL_NUM: 4 # PQ code stream num = 3 * HBM_CHANNEL_NUM
  STAGE5_COMP_PE_NUM: 12

  # stage 6
  # there could be a sorting network before the priority queue group (SORT_GROUP_ENABLE)
  #   if not, set SORT_GROUP_ENABLE to False, and SORT_GROUP_NUM to 0 or None
  # number of 16 outputs per cycle, e.g., HBM channel num = 10, comp PE num = 30, then 
  #   SORT_GROUP_NUM = 2; if HBM channel = 12, PE_num = 36, then SORT_GROUP_NUM = 3
  SORT_GROUP_ENABLE: False
  SORT_GROUP_NUM: 0 # only used when SORT_GROUP_ENABLE=True
  STAGE_6_PRIORITY_QUEUE_LEVEL: 2 # supported level num: 2 or 3
  # only fill STAGE_6_PRIORITY_QUEUE_L2_NUM, STAGE_6_STREAM_PER_L2_QUEUE_LARGER, STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  #   when STAGE_6_PRIORITY_QUEUE_LEVEL = 3, else left them blank
  # Must subject to: L1 stream num = (without sort-reduction unit) STAGE5_COMP_PE_NUM * 2 
  #                  or = (with sort reduction) 16 * 2
  # (STAGE_6_PRIORITY_QUEUE_L2_NUM - 1) * STAGE_6_STREAM_PER_L2_QUEUE_LARGER + STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: 2 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: 6 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: 4 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3

  # Dataset config
  DB_SCALE: 100M # 1M to 1000M
  FPGA_NUM: 1 # e.g., can use 8 FPGAs to serve 1000M dataset, each stores 125M vectors

  # Data directory (don't add "/" after the dir)
  #   e.g., dir=/home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks, 
  #     then the content for HBM0 is:
  #     /home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks/HBM_bank_0_raw
  # DATA_DIR: "/mnt/scratch/wenqi/saved_npy_data/FPGA_data_SIFT100M_IVF4096,PQ16_23_banks"
  # GT_DIR: "/mnt/scratch/wenqi/saved_npy_data/gnd/"

  # FPGA Settings
  DEVICE: U250 # Supported devices: U280, U250, U50
  FREQ: 140
