---
# U280_SIFT100M_K10_R60_55perc_140MHz_with_network

# best option name IVF4096,PQ16
# nprobe: 3
# QPS 30381.94444444444
# stage_option_list
# Stage 2:

#         HBM_bank: 0
#         BRAM_18K: 1.0
#         URAM: 120.0
#         FF: 172694
#         LUT: 134364
#         DSP48E: 870
        
# QPS: 31055.900621118017
# Cycles per query: 4508
# STAGE2_ON_CHIP: True
# STAGE2_OFF_CHIP_START_CHANNEL:None
# PE_NUM_CENTER_DIST_COMP: 15
# Stage 3:

#         HBM_bank: 0
#         BRAM_18K: 6.0
#         URAM: 0
#         FF: 2334.63
#         LUT: 2263.41
#         DSP48E: 0
        
# QPS: 34071.550255536626
# Cycles per query: 4109
# STAGE_3_PRIORITY_QUEUE_LEVEL: 2
# STAGE_3_PRIORITY_QUEUE_L1_NUM: 2
# Stage 4:

#         HBM_bank: 0
#         BRAM_18K: 73.0
#         URAM: 88
#         FF: 25583
#         LUT: 20487
#         DSP48E: 162
        
# QPS: 31876.138433515483
# Cycles per query: 4392
# PE_NUM_TABLE_CONSTRUCTION: 3
# Stage 5:

#         HBM_bank: 23.0
#         BRAM_18K: 483.0
#         URAM: 0.0
#         FF: 135263.0
#         LUT: 125840.66666666667
#         DSP48E: 690.0
        
# QPS: 30381.94444444444
# Cycles per query: 4608
# HBM_CHANNEL_NUM: 23
# STAGE5_COMP_PE_NUM: 23
# Stage 6:

#         HBM_bank: 0
#         BRAM_18K: 2.0
#         URAM: 0
#         FF: 83156.7
#         LUT: 77874.9
#         DSP48E: 0
        
# QPS: 39117.071807767534
# Cycles per query: 3579

# SORT_GROUP_ENABLE: True
# SORT_GROUP_NUM: 2
# STAGE_6_PRIORITY_QUEUE_LEVEL: 2
# STAGE_6_PRIORITY_QUEUE_L2_NUM: None
# STAGE_6_STREAM_PER_L2_QUEUE_LARGER: None
# STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: None
        
# total_valid_design: 15710875
# Total resource consumption:

#         HBM_bank: 23.0
#         BRAM_18K: 1934.0
#         URAM: 226.0
#         FF: 1006869.3300000001
#         LUT: 711986.9766666667
#         DSP48E: 1726.0
        
# Utilization rate:
# {'BRAM_18K': '47.96626984126984%', 'DSP48E': '19.12677304964539%', 'FF': '38.61642926178204%', 'LUT': '54.61363038987073%', 'URAM': '23.541666666666668%'}

  # Constants
  NLIST: 4096
  NPROBE: 3
  D: 128
  M: 16
  K: 256
  TOPK: 10

  QUERY_NUM: 10000

  LARGE_NUM: 99999999 # used to init the heap
  # stage 1
  OPQ_ENABLE: False
  OPQ_UNROLL_FACTOR: 4 # 4 or 8, the larger the better performance, left None if OPQ_ENABLE=False, only used when OPQ_ENABLE=True

  # stage 2
  # except last PE: compute more distances per query, last one compute less
  # e.g., nlist = 8192, PE num = 15, 
  #   each of the first 14 PEs construct 547 tables (8192 / 15 round up), 
  #   while the last constructs 534: 14 * 547 + 534 = 8192
  STAGE2_ON_CHIP: True
  STAGE2_OFF_CHIP_START_CHANNEL: None # Only used when STAGE2_ON_CHIP = True
  PE_NUM_CENTER_DIST_COMP: 15

  # stage 3
  STAGE_3_PRIORITY_QUEUE_LEVEL: 2 # support 1 or 2
  STAGE_3_PRIORITY_QUEUE_L1_NUM: 2 # only used when STAGE_3_PRIORITY_QUEUE_LEVEL=2

  # stage 4
  # except last PE: construct more tables per query, last one construct less
  # e.g., nprobe = 17, PE num = 6, each of the first 5 PEs construct 3 tables, 
  #   while the last constructs 2: 5 * 3 + 2 = 17
  PE_NUM_TABLE_CONSTRUCTION: 3

  # stage 5
  # (HBM_CHANNEL_NUM * 3 / STAGE5_COMP_PE_NUM) must be integar
  # e.g., default 1 HBM channel -> 3 PQ code streams -> STAGE5_COMP_PE_NUM = 3 * HBM_CHANNEL_NUM
  # e.g., merge content of 1 HBM channel to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM
  # e.g., merge content of 2 HBM channels to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM / 2
  HBM_CHANNEL_NUM: 23 # PQ code stream num = 3 * HBM_CHANNEL_NUM
  STAGE5_COMP_PE_NUM: 23

  # stage 6
  # there could be a sorting network before the priority queue group (SORT_GROUP_ENABLE)
  #   if not, set SORT_GROUP_ENABLE to False, and SORT_GROUP_NUM to 0 or None
  # number of 16 outputs per cycle, e.g., HBM channel num = 10, comp PE num = 30, then 
  #   SORT_GROUP_NUM = 2; if HBM channel = 12, PE_num = 36, then SORT_GROUP_NUM = 3
  SORT_GROUP_ENABLE: True
  SORT_GROUP_NUM: 2 # only used when SORT_GROUP_ENABLE=True
  STAGE_6_PRIORITY_QUEUE_LEVEL: 2 # supported level num: 2 or 3
  # only fill STAGE_6_PRIORITY_QUEUE_L2_NUM, STAGE_6_STREAM_PER_L2_QUEUE_LARGER, STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  #   when STAGE_6_PRIORITY_QUEUE_LEVEL = 3, else left them blank
  # Must subject to: L1 stream num = (without sort-reduction unit) STAGE5_COMP_PE_NUM * 2 
  #                  or = (with sort reduction) 16 * 2
  # (STAGE_6_PRIORITY_QUEUE_L2_NUM - 1) * STAGE_6_STREAM_PER_L2_QUEUE_LARGER + STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: 2 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: 6 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: 4 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3

  # Dataset config
  DB_SCALE: "100M" # 1M to 1000M

  # Data directory (don't add "/" after the dir)
  #   e.g., dir=/home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks, 
  #     then the content for HBM0 is:
  #     /home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks/HBM_bank_0_raw
  DATA_DIR: "/mnt/scratch/wenqi/saved_npy_data/FPGA_data_SIFT100M_IVF4096,PQ16_23_banks"
  GT_DIR: "/mnt/scratch/wenqi/saved_npy_data/gnd/"

  # FPGA Settings
  DEVICE: U280 # Supported devices: U280, U250, U50
  FREQ: 140