---

    # 
  # 
  # ======== Result =========
  # 
  # best option name nlist_8192_nprobe_17_OPQ_1
  # nprobe: 17
  # QPS 7142.492729962757
  # stage_option_list
  # Stage 1:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 37
  #         URAM: 0
  #         FF: 2659
  #         LUT: 2152
  #         DSP48E: 20
  #         
  # QPS: 32014.635261833984
  # Cycles per query: 4373.0
  # OPQ_ENABLE: True
  # OPQ_UNROLL_FACTOR: 4
  # Stage 2:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 1.0
  #         URAM: 168.0
  #         FF: 80654
  #         LUT: 62796
  #         DSP48E: 406
  #         
  # QPS: 7421.543681085666
  # Cycles per query: 18864
  # STAGE2_ON_CHIP: True
  # STAGE2_OFF_CHIP_START_CHANNEL:None
  # PE_NUM_CENTER_DIST_COMP: 7
  # Stage 3:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 1.0
  #         URAM: 0
  #         FF: 3428.19
  #         LUT: 3717.33
  #         DSP48E: 0
  #         
  # QPS: 8530.863445250137
  # Cycles per query: 16411
  # STAGE_3_PRIORITY_QUEUE_LEVEL: 1
  # STAGE_3_PRIORITY_QUEUE_L1_NUM: 1
  # Stage 4:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 271.0
  #         URAM: 168
  #         FF: 56825
  #         LUT: 42209
  #         DSP48E: 270
  #         
  # QPS: 8147.113594040969
  # Cycles per query: 17184
  # PE_NUM_TABLE_CONSTRUCTION: 5
  # Stage 5:
  # 
  #         HBM_bank: 17.0
  #         BRAM_18K: 357.0
  #         URAM: 0.0
  #         FF: 99977.0
  #         LUT: 93012.66666666667
  #         DSP48E: 510.0
  #         
  # QPS: 7142.492729962757
  # Cycles per query: 19601
  # HBM_CHANNEL_NUM: 17
  # STAGE5_COMP_PE_NUM: 17
  # Stage 6:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 70.0
  #         URAM: 0
  #         FF: 349772.5
  #         LUT: 380887.5
  #         DSP48E: 0
  #         
  # QPS: 10048.808498420902
  # Cycles per query: 13932
  # 
  # SORT_GROUP_ENABLE: False
  # SORT_GROUP_NUM: None
  # STAGE_6_PRIORITY_QUEUE_LEVEL: 2
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: None
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: None
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: None
  #         
  # total_valid_design: 650649
  # Total resource consumption: (with shell)
  # 
  #         HBM_bank: 17.0
  #         BRAM_18K: 1177.0
  #         URAM: 336.0
  #         FF: 917459.69
  #         LUT: 778535.4966666667
  #         DSP48E: 1210.0
  #         
  # Total resource consumption: (accelerator kernel without shell)
  # 
  #         HBM_bank: 17.0
  #         BRAM_18K: 737.0
  #         URAM: 336.0
  #         FF: 593315.69
  #         LUT: 584774.4966666667
  #         DSP48E: 1206.0
  #         
  # 
  # Per Stage Utilization rate (Total = FPGA):
  # Stage 1: {'BRAM_18K': '0.9176587301587302%', 'DSP48E': '0.22163120567375888%', 'FF': '0.10198054737358862%', 'LUT': '0.16507118311242022%', 'URAM': '0.0%'}
  # Stage 2: {'BRAM_18K': '0.0248015873015873%', 'DSP48E': '4.499113475177305%', 'FF': '3.093320446735395%', 'LUT': '4.8168262150220915%', 'URAM': '17.5%'}
  # Stage 3: {'BRAM_18K': '0.0248015873015873%', 'DSP48E': '0.0%', 'FF': '0.13148126840942564%', 'LUT': '0.28514129234167895%', 'URAM': '0.0%'}
  # Stage 4: {'BRAM_18K': '6.721230158730158%', 'DSP48E': '2.992021276595745%', 'FF': '2.1794075233186057%', 'LUT': '3.237681026018655%', 'URAM': '17.5%'}
  # Stage 5: {'BRAM_18K': '8.854166666666668%', 'DSP48E': '5.651595744680852%', 'FF': '3.8344148870888564%', 'LUT': '7.134624038618885%', 'URAM': '0.0%'}
  # Stage 6: {'BRAM_18K': '1.7361111111111112%', 'DSP48E': '0.0%', 'FF': '13.414814218213058%', 'LUT': '29.2163337628866%', 'URAM': '0.0%'}
  # 
  # Per Stage Utilization rate (Total = Accelerator Kernel (without shell)):
  # Stage 1: {'BRAM_18K': '5.020352781546811%', 'DSP48E': '1.658374792703151%', 'FF': '0.4481593938633243%', 'LUT': '0.36800510491938976%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 1: 0.36800510491938976%
  # Stage 2: {'BRAM_18K': '0.13568521031207598%', 'DSP48E': '33.66500829187397%', 'FF': '13.59377501039961%', 'LUT': '10.738498405445167%', 'URAM': '50.0%'}
  # LUT only:
  # Stage 2: 10.738498405445167%
  # Stage 3: {'BRAM_18K': '0.13568521031207598%', 'DSP48E': '0.0%', 'FF': '0.5778020129553628%', 'LUT': '0.6356860672258341%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 3: 0.6356860672258341%
  # Stage 4: {'BRAM_18K': '36.77069199457259%', 'DSP48E': '22.388059701492537%', 'FF': '9.577531988071982%', 'LUT': '7.217996037891507%', 'URAM': '50.0%'}
  # LUT only:
  # Stage 4: 7.217996037891507%
  # Stage 5: {'BRAM_18K': '48.43962008141113%', 'DSP48E': '42.28855721393035%', 'FF': '16.850557247188256%', 'LUT': '15.905732414265284%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 5: 15.905732414265284%
  # Stage 6: {'BRAM_18K': '9.49796472184532%', 'DSP48E': '0.0%', 'FF': '58.95217434752147%', 'LUT': '65.13408197025281%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 6: 65.13408197025281%
  # 
  # Total Utilization rate:
  # {'BRAM_18K': '29.191468253968257%', 'DSP48E': '13.408687943262413%', 'FF': '35.187304016323026%', 'LUT': '59.7182971792669%', 'URAM': '35.0%'}


  # Constants
  NLIST: 8192
  NPROBE: 17
  D: 128
  M: 16
  K: 256
  TOPK: 50

  QUERY_NUM: 10000

  LARGE_NUM: 99999999 # used to init the heap
  # stage 1
  OPQ_ENABLE: 1
  OPQ_UNROLL_FACTOR: 4 # 4 or 8, the larger the better performance, left None if OPQ_ENABLE=False, only used when OPQ_ENABLE=True

  # stage 2
  # except last PE: compute more distances per query, last one compute less
  # e.g., nlist = 8192, PE num = 15, 
  #   each of the first 14 PEs construct 547 tables (8192 / 15 round up), 
  #   while the last constructs 534: 14 * 547 + 534 = 8192
  STAGE2_ON_CHIP: True
  PE_NUM_CENTER_DIST_COMP: 7

  # stage 3
  STAGE_3_PRIORITY_QUEUE_LEVEL: 1 # support 1 or 2
  STAGE_3_PRIORITY_QUEUE_L1_NUM: 1 # only used when STAGE_3_PRIORITY_QUEUE_LEVEL=2

  # stage 4
  # except last PE: construct more tables per query, last one construct less
  # e.g., nprobe = 17, PE num = 6, each of the first 5 PEs construct 3 tables, 
  #   while the last constructs 2: 5 * 3 + 2 = 17
  PE_NUM_TABLE_CONSTRUCTION: 5

  # stage 5
  # (HBM_CHANNEL_NUM * 3 / STAGE5_COMP_PE_NUM) must be integar
  # e.g., default 1 HBM channel -> 3 PQ code streams -> STAGE5_COMP_PE_NUM = 3 * HBM_CHANNEL_NUM
  # e.g., merge content of 1 HBM channel to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM
  # e.g., merge content of 2 HBM channels to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM / 2
  HBM_CHANNEL_NUM: 17 # PQ code stream num = 3 * HBM_CHANNEL_NUM
  STAGE5_COMP_PE_NUM: 17

  # stage 6
  # there could be a sorting network before the priority queue group (SORT_GROUP_ENABLE)
  #   if not, set SORT_GROUP_ENABLE to False, and SORT_GROUP_NUM to 0 or None
  # number of 16 outputs per cycle, e.g., HBM channel num = 10, comp PE num = 30, then 
  #   SORT_GROUP_NUM = 2; if HBM channel = 12, PE_num = 36, then SORT_GROUP_NUM = 3
  SORT_GROUP_ENABLE: False
  SORT_GROUP_NUM: 0 # only used when SORT_GROUP_ENABLE=True
  STAGE_6_PRIORITY_QUEUE_LEVEL: 2 # supported level num: 2 or 3
  # only fill STAGE_6_PRIORITY_QUEUE_L2_NUM, STAGE_6_STREAM_PER_L2_QUEUE_LARGER, STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  #   when STAGE_6_PRIORITY_QUEUE_LEVEL = 3, else left them blank
  # Must subject to: L1 stream num = (without sort-reduction unit) STAGE5_COMP_PE_NUM * 2 
  #                  or = (with sort reduction) 16 * 2
  # (STAGE_6_PRIORITY_QUEUE_L2_NUM - 1) * STAGE_6_STREAM_PER_L2_QUEUE_LARGER + STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: 2 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: 6 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: 4 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3

  # Dataset config
  DB_SCALE: 100M # 1M to 1000M
  FPGA_NUM: 1 # e.g., can use 8 FPGAs to serve 1000M dataset, each stores 125M vectors

  # Data directory (don't add "/" after the dir)
  #   e.g., dir=/home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks, 
  #     then the content for HBM0 is:
  #     /home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks/HBM_bank_0_raw
  # DATA_DIR: "/mnt/scratch/wenqi/saved_npy_data/FPGA_data_SIFT100M_IVF4096,PQ16_23_banks"
  # GT_DIR: "/mnt/scratch/wenqi/saved_npy_data/gnd/"

  # FPGA Settings
  DEVICE: U280 # Supported devices: U280, U250, U50
  FREQ: 140
