---

    # 
  # 
  # ======== Result =========
  # 
  # best option name OPQ16,IVF65536,PQ16
  # nprobe: 30
  # QPS 2131.7416329140906
  # stage_option_list
  # Stage 1:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 37
  #         URAM: 0
  #         FF: 2659
  #         LUT: 2152
  #         DSP48E: 20
  #         
  # QPS: 32014.635261833984
  # Cycles per query: 4373.0
  # OPQ_ENABLE: True
  # OPQ_UNROLL_FACTOR: 4
  # Stage 2:
  # 
  #         HBM_bank: 8
  #         BRAM_18K: 1.0
  #         URAM: 0
  #         FF: 184199
  #         LUT: 143310
  #         DSP48E: 928
  #         
  # QPS: 2131.7416329140906
  # Cycles per query: 65674
  # STAGE2_ON_CHIP: False
  # STAGE2_OFF_CHIP_START_CHANNEL:None
  # PE_NUM_CENTER_DIST_COMP: 16
  # Stage 3:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 6.0
  #         URAM: 0
  #         FF: 18216.3
  #         LUT: 19718.100000000002
  #         DSP48E: 0
  #         
  # QPS: 2134.927412467976
  # Cycles per query: 65576
  # STAGE_3_PRIORITY_QUEUE_LEVEL: 2
  # STAGE_3_PRIORITY_QUEUE_L1_NUM: 2
  # Stage 4:
  # 
  #         HBM_bank: 1
  #         BRAM_18K: 278.0
  #         URAM: 16
  #         FF: 38842
  #         LUT: 26042
  #         DSP48E: 108
  #         
  # QPS: 2184.4963175633507
  # Cycles per query: 64088
  # PE_NUM_TABLE_CONSTRUCTION: 2
  # Stage 5:
  # 
  #         HBM_bank: 9.0
  #         BRAM_18K: 63.0
  #         URAM: 0.0
  #         FF: 17643.0
  #         LUT: 16414.0
  #         DSP48E: 90.0
  #         
  # QPS: 5162.241887905605
  # Cycles per query: 27120.0
  # HBM_CHANNEL_NUM: 9
  # STAGE5_COMP_PE_NUM: 3.0
  # Stage 6:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 14.0
  #         URAM: 0
  #         FF: 15054.899999999998
  #         LUT: 15840.300000000001
  #         DSP48E: 0
  #         
  # QPS: 8022.922636103151
  # Cycles per query: 17450
  # 
  # SORT_GROUP_ENABLE: False
  # SORT_GROUP_NUM: None
  # STAGE_6_PRIORITY_QUEUE_LEVEL: 2
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: None
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: None
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: None
  #         
  # total_valid_design: 133737
  # Total resource consumption: (with shell)
  # 
  #         HBM_bank: 18.0
  #         BRAM_18K: 839.0
  #         URAM: 16.0
  #         FF: 600758.2
  #         LUT: 417237.4
  #         DSP48E: 1150.0
  #         
  # Total resource consumption: (accelerator kernel without shell)
  # 
  #         HBM_bank: 18.0
  #         BRAM_18K: 399.0
  #         URAM: 16.0
  #         FF: 276614.2
  #         LUT: 223476.4
  #         DSP48E: 1146.0
  #         
  # 
  # Per Stage Utilization rate (Total = FPGA):
  # Stage 1: {'BRAM_18K': '0.9176587301587302%', 'DSP48E': '0.22163120567375888%', 'FF': '0.10198054737358862%', 'LUT': '0.16507118311242022%', 'URAM': '0.0%'}
  # Stage 2: {'BRAM_18K': '0.0248015873015873%', 'DSP48E': '10.28368794326241%', 'FF': '7.064578730976927%', 'LUT': '10.992728276877761%', 'URAM': '0.0%'}
  # Stage 3: {'BRAM_18K': '0.1488095238095238%', 'DSP48E': '0.0%', 'FF': '0.6986492083946981%', 'LUT': '1.5124953976435938%', 'URAM': '0.0%'}
  # Stage 4: {'BRAM_18K': '6.894841269841271%', 'DSP48E': '1.196808510638298%', 'FF': '1.4897060628375063%', 'LUT': '1.997576092292587%', 'URAM': '1.6666666666666667%'}
  # Stage 5: {'BRAM_18K': '1.5625%', 'DSP48E': '0.9973404255319149%', 'FF': '0.6766614506627393%', 'LUT': '1.2590513009327442%', 'URAM': '0.0%'}
  # Stage 6: {'BRAM_18K': '0.3472222222222222%', 'DSP48E': '0.0%', 'FF': '0.5774001288659794%', 'LUT': '1.2150451030927836%', 'URAM': '0.0%'}
  # 
  # Per Stage Utilization rate (Total = Accelerator Kernel (without shell)):
  # Stage 1: {'BRAM_18K': '9.273182957393484%', 'DSP48E': '1.7452006980802792%', 'FF': '0.9612666305634345%', 'LUT': '0.96296521690881%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 1: 0.96296521690881%
  # Stage 2: {'BRAM_18K': '0.2506265664160401%', 'DSP48E': '80.97731239092496%', 'FF': '66.59057994853481%', 'LUT': '64.12757678215686%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 2: 64.12757678215686%
  # Stage 3: {'BRAM_18K': '1.5037593984962405%', 'DSP48E': '0.0%', 'FF': '6.585453675190934%', 'LUT': '8.823347789744243%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 3: 8.823347789744243%
  # Stage 4: {'BRAM_18K': '69.67418546365914%', 'DSP48E': '9.424083769633508%', 'FF': '14.041940001634043%', 'LUT': '11.653132053317487%', 'URAM': '100.0%'}
  # LUT only:
  # Stage 4: 11.653132053317487%
  # Stage 5: {'BRAM_18K': '15.789473684210526%', 'DSP48E': '7.853403141361256%', 'FF': '6.378197503960389%', 'LUT': '7.344847151645544%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 5: 7.344847151645544%
  # Stage 6: {'BRAM_18K': '3.508771929824561%', 'DSP48E': '0.0%', 'FF': '5.442562240116377%', 'LUT': '7.088131006227057%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 6: 7.088131006227057%
  # 
  # Total Utilization rate:
  # {'BRAM_18K': '20.808531746031747%', 'DSP48E': '12.743794326241135%', 'FF': '23.040861254295532%', 'LUT': '32.00458701521846%', 'URAM': '1.6666666666666667%'}


  # Constants
  NLIST: 65536
  NPROBE: 30
  D: 128
  M: 16
  K: 256
  TOPK: 10

  QUERY_NUM: 10000

  LARGE_NUM: 99999999 # used to init the heap
  # stage 1
  OPQ_ENABLE: True
  OPQ_UNROLL_FACTOR: 4 # 4 or 8, the larger the better performance, left None if OPQ_ENABLE=False, only used when OPQ_ENABLE=True

  # stage 2
  # except last PE: compute more distances per query, last one compute less
  # e.g., nlist = 8192, PE num = 15, 
  #   each of the first 14 PEs construct 547 tables (8192 / 15 round up), 
  #   while the last constructs 534: 14 * 547 + 534 = 8192
  STAGE2_ON_CHIP: False
  PE_NUM_CENTER_DIST_COMP: 16

  # stage 3
  STAGE_3_PRIORITY_QUEUE_LEVEL: 2 # support 1 or 2
  STAGE_3_PRIORITY_QUEUE_L1_NUM: 2 # only used when STAGE_3_PRIORITY_QUEUE_LEVEL=2

  # stage 4
  # except last PE: construct more tables per query, last one construct less
  # e.g., nprobe = 17, PE num = 6, each of the first 5 PEs construct 3 tables, 
  #   while the last constructs 2: 5 * 3 + 2 = 17
  PE_NUM_TABLE_CONSTRUCTION: 2

  # stage 5
  # (HBM_CHANNEL_NUM * 3 / STAGE5_COMP_PE_NUM) must be integar
  # e.g., default 1 HBM channel -> 3 PQ code streams -> STAGE5_COMP_PE_NUM = 3 * HBM_CHANNEL_NUM
  # e.g., merge content of 1 HBM channel to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM
  # e.g., merge content of 2 HBM channels to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM / 2
  HBM_CHANNEL_NUM: 9 # PQ code stream num = 3 * HBM_CHANNEL_NUM
  STAGE5_COMP_PE_NUM: 3

  # stage 6
  # there could be a sorting network before the priority queue group (SORT_GROUP_ENABLE)
  #   if not, set SORT_GROUP_ENABLE to False, and SORT_GROUP_NUM to 0 or None
  # number of 16 outputs per cycle, e.g., HBM channel num = 10, comp PE num = 30, then 
  #   SORT_GROUP_NUM = 2; if HBM channel = 12, PE_num = 36, then SORT_GROUP_NUM = 3
  SORT_GROUP_ENABLE: False
  SORT_GROUP_NUM: 0 # only used when SORT_GROUP_ENABLE=True
  STAGE_6_PRIORITY_QUEUE_LEVEL: 2 # supported level num: 2 or 3
  # only fill STAGE_6_PRIORITY_QUEUE_L2_NUM, STAGE_6_STREAM_PER_L2_QUEUE_LARGER, STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  #   when STAGE_6_PRIORITY_QUEUE_LEVEL = 3, else left them blank
  # Must subject to: L1 stream num = (without sort-reduction unit) STAGE5_COMP_PE_NUM * 2 
  #                  or = (with sort reduction) 16 * 2
  # (STAGE_6_PRIORITY_QUEUE_L2_NUM - 1) * STAGE_6_STREAM_PER_L2_QUEUE_LARGER + STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: 2 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: 6 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: 4 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3

  # Dataset config
  DB_SCALE: 100M # 1M to 1000M
  FPGA_NUM: 1 # e.g., can use 8 FPGAs to serve 1000M dataset, each stores 125M vectors

  # Data directory (don't add "/" after the dir)
  #   e.g., dir=/home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks, 
  #     then the content for HBM0 is:
  #     /home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks/HBM_bank_0_raw
  # DATA_DIR: "/mnt/scratch/wenqi/saved_npy_data/FPGA_data_SIFT100M_IVF4096,PQ16_23_banks"
  # GT_DIR: "/mnt/scratch/wenqi/saved_npy_data/gnd/"

  # FPGA Settings
  DEVICE: U280 # Supported devices: U280, U250, U50
  FREQ: 140
