---

    # 
  # 
  # ======== Result =========
  # 
  # best option name IVF65536,PQ16
  # nprobe: 33
  # QPS 2131.7416329140906
  # stage_option_list
  # Stage 2:
  # 
  #         HBM_bank: 8
  #         BRAM_18K: 1.0
  #         URAM: 0
  #         FF: 184199
  #         LUT: 143310
  #         DSP48E: 928
  #         
  # QPS: 2131.7416329140906
  # Cycles per query: 65674
  # STAGE2_ON_CHIP: False
  # STAGE2_OFF_CHIP_START_CHANNEL:None
  # PE_NUM_CENTER_DIST_COMP: 16
  # Stage 3:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 6.0
  #         URAM: 0
  #         FF: 19980.93
  #         LUT: 21657.510000000002
  #         DSP48E: 0
  #         
  # QPS: 2134.8297473276507
  # Cycles per query: 65579
  # STAGE_3_PRIORITY_QUEUE_LEVEL: 2
  # STAGE_3_PRIORITY_QUEUE_L1_NUM: 2
  # Stage 4:
  # 
  #         HBM_bank: 1
  #         BRAM_18K: 313.0
  #         URAM: 24
  #         FF: 48383
  #         LUT: 33447
  #         DSP48E: 162
  #         
  # QPS: 2976.6967171287633
  # Cycles per query: 47032
  # PE_NUM_TABLE_CONSTRUCTION: 3
  # Stage 5:
  # 
  #         HBM_bank: 9.0
  #         BRAM_18K: 63.0
  #         URAM: 0.0
  #         FF: 17643.0
  #         LUT: 16414.0
  #         DSP48E: 90.0
  #         
  # QPS: 4692.947170823278
  # Cycles per query: 29832
  # HBM_CHANNEL_NUM: 9
  # STAGE5_COMP_PE_NUM: 3
  # Stage 6:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 14.0
  #         URAM: 0
  #         FF: 15054.899999999998
  #         LUT: 15840.300000000001
  #         DSP48E: 0
  #         
  # QPS: 7294.706127553147
  # Cycles per query: 19192
  # 
  # SORT_GROUP_ENABLE: False
  # SORT_GROUP_NUM: None
  # STAGE_6_PRIORITY_QUEUE_LEVEL: 2
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: None
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: None
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: None
  #         
  # total_valid_design: 70555
  # Total resource consumption: (with shell)
  # 
  #         HBM_bank: 18.0
  #         BRAM_18K: 837.0
  #         URAM: 24.0
  #         FF: 609404.8300000001
  #         LUT: 424429.81
  #         DSP48E: 1184.0
  #         
  # Total resource consumption: (accelerator kernel without shell)
  # 
  #         HBM_bank: 18.0
  #         BRAM_18K: 397.0
  #         URAM: 24.0
  #         FF: 285260.83
  #         LUT: 230668.81
  #         DSP48E: 1180.0
  #         
  # Per Stage Utilization rate (Total = FPGA):
  # 
  # Stage 2: {'BRAM_18K': '0.0248015873015873%', 'DSP48E': '10.28368794326241%', 'FF': '7.064578730976927%', 'LUT': '10.992728276877761%', 'URAM': '0.0%'}
  # Stage 3: {'BRAM_18K': '0.1488095238095238%', 'DSP48E': '0.0%', 'FF': '0.7663280099410898%', 'LUT': '1.661259664948454%', 'URAM': '0.0%'}
  # Stage 4: {'BRAM_18K': '7.762896825396826%', 'DSP48E': '1.795212765957447%', 'FF': '1.8556317501227295%', 'LUT': '2.565583578792342%', 'URAM': '2.5%'}
  # Stage 5: {'BRAM_18K': '1.5625%', 'DSP48E': '0.9973404255319149%', 'FF': '0.6766614506627393%', 'LUT': '1.2590513009327442%', 'URAM': '0.0%'}
  # Stage 6: {'BRAM_18K': '0.3472222222222222%', 'DSP48E': '0.0%', 'FF': '0.5774001288659794%', 'LUT': '1.2150451030927836%', 'URAM': '0.0%'}
  # Per Stage Utilization rate (Total = Accelerator Kernel (without shell)):
  # 
  # Stage 2: {'BRAM_18K': '0.2518891687657431%', 'DSP48E': '78.64406779661017%', 'FF': '64.57213210800795%', 'LUT': '62.12803542880375%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 2: 62.12803542880375%
  # Stage 3: {'BRAM_18K': '1.5113350125944585%', 'DSP48E': '0.0%', 'FF': '7.00444221521756%', 'LUT': '9.389006688854034%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 3: 9.389006688854034%
  # Stage 4: {'BRAM_18K': '78.84130982367759%', 'DSP48E': '13.728813559322035%', 'FF': '16.96096866856904%', 'LUT': '14.500009775920725%', 'URAM': '100.0%'}
  # LUT only:
  # Stage 4: 14.500009775920725%
  # Stage 5: {'BRAM_18K': '15.869017632241814%', 'DSP48E': '7.627118644067797%', 'FF': '6.184865969856429%', 'LUT': '7.115829834124518%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 5: 7.115829834124518%
  # Stage 6: {'BRAM_18K': '3.5264483627204033%', 'DSP48E': '0.0%', 'FF': '5.277591038349008%', 'LUT': '6.867118272296979%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 6: 6.867118272296979%
  # Total Utilization rate:
  # {'BRAM_18K': '20.758928571428573%', 'DSP48E': '13.120567375886525%', 'FF': '23.372485195753562%', 'LUT': '32.55628758591065%', 'URAM': '2.5%'}


  # Constants
  NLIST: 65536
  NPROBE: 33
  D: 128
  M: 16
  K: 256
  TOPK: 10

  QUERY_NUM: 10000

  LARGE_NUM: 99999999 # used to init the heap
  # stage 1
  OPQ_ENABLE: False
  OPQ_UNROLL_FACTOR: <--OPQ_unroll_factor--> # 4 or 8, the larger the better performance, left None if OPQ_ENABLE=False, only used when OPQ_ENABLE=True

  # stage 2
  # except last PE: compute more distances per query, last one compute less
  # e.g., nlist = 8192, PE num = 15, 
  #   each of the first 14 PEs construct 547 tables (8192 / 15 round up), 
  #   while the last constructs 534: 14 * 547 + 534 = 8192
  STAGE2_ON_CHIP: False
  PE_NUM_CENTER_DIST_COMP: 16

  # stage 3
  STAGE_3_PRIORITY_QUEUE_LEVEL: 2 # support 1 or 2
  STAGE_3_PRIORITY_QUEUE_L1_NUM: 2 # only used when STAGE_3_PRIORITY_QUEUE_LEVEL=2

  # stage 4
  # except last PE: construct more tables per query, last one construct less
  # e.g., nprobe = 17, PE num = 6, each of the first 5 PEs construct 3 tables, 
  #   while the last constructs 2: 5 * 3 + 2 = 17
  PE_NUM_TABLE_CONSTRUCTION: 3

  # stage 5
  # (HBM_CHANNEL_NUM * 3 / STAGE5_COMP_PE_NUM) must be integar
  # e.g., default 1 HBM channel -> 3 PQ code streams -> STAGE5_COMP_PE_NUM = 3 * HBM_CHANNEL_NUM
  # e.g., merge content of 1 HBM channel to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM
  # e.g., merge content of 2 HBM channels to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM / 2
  HBM_CHANNEL_NUM: 9 # PQ code stream num = 3 * HBM_CHANNEL_NUM
  STAGE5_COMP_PE_NUM: 3

  # stage 6
  # there could be a sorting network before the priority queue group (SORT_GROUP_ENABLE)
  #   if not, set SORT_GROUP_ENABLE to False, and SORT_GROUP_NUM to 0 or None
  # number of 16 outputs per cycle, e.g., HBM channel num = 10, comp PE num = 30, then 
  #   SORT_GROUP_NUM = 2; if HBM channel = 12, PE_num = 36, then SORT_GROUP_NUM = 3
  SORT_GROUP_ENABLE: False
  SORT_GROUP_NUM: 0 # only used when SORT_GROUP_ENABLE=True
  STAGE_6_PRIORITY_QUEUE_LEVEL: 2 # supported level num: 2 or 3
  # only fill STAGE_6_PRIORITY_QUEUE_L2_NUM, STAGE_6_STREAM_PER_L2_QUEUE_LARGER, STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  #   when STAGE_6_PRIORITY_QUEUE_LEVEL = 3, else left them blank
  # Must subject to: L1 stream num = (without sort-reduction unit) STAGE5_COMP_PE_NUM * 2 
  #                  or = (with sort reduction) 16 * 2
  # (STAGE_6_PRIORITY_QUEUE_L2_NUM - 1) * STAGE_6_STREAM_PER_L2_QUEUE_LARGER + STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: 2 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: 6 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: 4 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3

  # Dataset config
  DB_SCALE: 100M # 1M to 1000M
  FPGA_NUM: 1 # e.g., can use 8 FPGAs to serve 1000M dataset, each stores 125M vectors

  # Data directory (don't add "/" after the dir)
  #   e.g., dir=/home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks, 
  #     then the content for HBM0 is:
  #     /home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks/HBM_bank_0_raw
  # DATA_DIR: "/mnt/scratch/wenqi/saved_npy_data/FPGA_data_SIFT100M_IVF4096,PQ16_23_banks"
  # GT_DIR: "/mnt/scratch/wenqi/saved_npy_data/gnd/"

  # FPGA Settings
  DEVICE: U280 # Supported devices: U280, U250, U50
  FREQ: 140
