---

    # 
  # 
  # ======== Result =========
  # 
  # best option name IVF4096,PQ16
  # nprobe: 5
  # QPS 31876.138433515483
  # stage_option_list
  # Stage 2:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 1.0
  #         URAM: 128.0
  #         FF: 184199
  #         LUT: 143310
  #         DSP48E: 928
  #         
  # QPS: 33065.658951346246
  # Cycles per query: 4234
  # STAGE2_ON_CHIP: True
  # STAGE2_OFF_CHIP_START_CHANNEL:None
  # PE_NUM_CENTER_DIST_COMP: 16
  # Stage 3:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 6.0
  #         URAM: 0
  #         FF: 3511.0499999999997
  #         LUT: 3556.3500000000004
  #         DSP48E: 0
  #         
  # QPS: 34054.97445876915
  # Cycles per query: 4111
  # STAGE_3_PRIORITY_QUEUE_LEVEL: 2
  # STAGE_3_PRIORITY_QUEUE_L1_NUM: 2
  # Stage 4:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 111.0
  #         URAM: 104
  #         FF: 41625
  #         LUT: 33569
  #         DSP48E: 270
  #         
  # QPS: 31876.138433515483
  # Cycles per query: 4392
  # PE_NUM_TABLE_CONSTRUCTION: 5
  # Stage 5:
  # 
  #         HBM_bank: 19.0
  #         BRAM_18K: 1197.0
  #         URAM: 0.0
  #         FF: 335217.0
  #         LUT: 311866.0
  #         DSP48E: 1710.0
  #         
  # QPS: 32596.04190919674
  # Cycles per query: 4295
  # HBM_CHANNEL_NUM: 19
  # STAGE5_COMP_PE_NUM: 57
  # Stage 6:
  # 
  #         HBM_bank: 0
  #         BRAM_18K: 230.0
  #         URAM: 0
  #         FF: 44398.05
  #         LUT: 37201.350000000006
  #         DSP48E: 0
  #         
  # QPS: 57827.34407269723
  # Cycles per query: 2421
  # 
  # SORT_GROUP_ENABLE: False
  # SORT_GROUP_NUM: None
  # STAGE_6_PRIORITY_QUEUE_LEVEL: 2
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: None
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: None
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: None
  #         
  # total_valid_design: 16729018
  # Total resource consumption: (with shell)
  # 
  #         HBM_bank: 19.0
  #         BRAM_18K: 1985.0
  #         URAM: 232.0
  #         FF: 933094.1000000001
  #         LUT: 723263.7
  #         DSP48E: 2912.0
  #         
  # Total resource consumption: (accelerator kernel without shell)
  # 
  #         HBM_bank: 19.0
  #         BRAM_18K: 1545.0
  #         URAM: 232.0
  #         FF: 608950.1000000001
  #         LUT: 529502.7
  #         DSP48E: 2908.0
  #         
  # Per Stage Utilization rate (Total = FPGA):
  # 
  # Stage 2: {'BRAM_18K': '0.0248015873015873%', 'DSP48E': '10.28368794326241%', 'FF': '7.064578730976927%', 'LUT': '10.992728276877761%', 'URAM': '13.333333333333334%'}
  # Stage 3: {'BRAM_18K': '0.1488095238095238%', 'DSP48E': '0.0%', 'FF': '0.13465919550810013%', 'LUT': '0.2727931701030928%', 'URAM': '0.0%'}
  # Stage 4: {'BRAM_18K': '2.7529761904761902%', 'DSP48E': '2.992021276595745%', 'FF': '1.5964423784977908%', 'LUT': '2.5749417034855178%', 'URAM': '10.833333333333334%'}
  # Stage 5: {'BRAM_18K': '29.6875%', 'DSP48E': '18.949468085106382%', 'FF': '12.856567562592048%', 'LUT': '23.92197471772214%', 'URAM': '0.0%'}
  # Stage 6: {'BRAM_18K': '5.704365079365079%', 'DSP48E': '0.0%', 'FF': '1.7027970821060383%', 'LUT': '2.8535645250368193%', 'URAM': '0.0%'}
  # Per Stage Utilization rate (Total = Accelerator Kernel (without shell)):
  # 
  # Stage 2: {'BRAM_18K': '0.06472491909385113%', 'DSP48E': '31.911966987620353%', 'FF': '30.248619714488918%', 'LUT': '27.065017798776097%', 'URAM': '55.172413793103445%'}
  # LUT only:
  # Stage 2: 27.065017798776097%
  # Stage 3: {'BRAM_18K': '0.3883495145631068%', 'DSP48E': '0.0%', 'FF': '0.5765743367149457%', 'LUT': '0.6716396346987467%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 3: 0.6716396346987467%
  # Stage 4: {'BRAM_18K': '7.184466019417475%', 'DSP48E': '9.284731774415405%', 'FF': '6.835535456846134%', 'LUT': '6.339722158168411%', 'URAM': '44.827586206896555%'}
  # LUT only:
  # Stage 4: 6.339722158168411%
  # Stage 5: {'BRAM_18K': '77.47572815533981%', 'DSP48E': '58.803301237964234%', 'FF': '55.048352894596775%', 'LUT': '58.897905525316496%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 5: 58.897905525316496%
  # Stage 6: {'BRAM_18K': '14.886731391585762%', 'DSP48E': '0.0%', 'FF': '7.290917597353215%', 'LUT': '7.0257148830402585%', 'URAM': '0.0%'}
  # LUT only:
  # Stage 6: 7.0257148830402585%
  # Total Utilization rate:
  # {'BRAM_18K': '49.2311507936508%', 'DSP48E': '32.269503546099294%', 'FF': '35.786930074865005%', 'LUT': '55.4786220544919%', 'URAM': '24.166666666666668%'}


  # Constants
  NLIST: 4096
  NPROBE: 5
  D: 128
  M: 16
  K: 256
  TOPK: 1

  QUERY_NUM: 10000

  LARGE_NUM: 99999999 # used to init the heap
  # stage 1
  OPQ_ENABLE: False
  OPQ_UNROLL_FACTOR: <--OPQ_unroll_factor--> # 4 or 8, the larger the better performance, left None if OPQ_ENABLE=False, only used when OPQ_ENABLE=True

  # stage 2
  # except last PE: compute more distances per query, last one compute less
  # e.g., nlist = 8192, PE num = 15, 
  #   each of the first 14 PEs construct 547 tables (8192 / 15 round up), 
  #   while the last constructs 534: 14 * 547 + 534 = 8192
  STAGE2_ON_CHIP: True
  PE_NUM_CENTER_DIST_COMP: 16

  # stage 3
  STAGE_3_PRIORITY_QUEUE_LEVEL: 2 # support 1 or 2
  STAGE_3_PRIORITY_QUEUE_L1_NUM: 2 # only used when STAGE_3_PRIORITY_QUEUE_LEVEL=2

  # stage 4
  # except last PE: construct more tables per query, last one construct less
  # e.g., nprobe = 17, PE num = 6, each of the first 5 PEs construct 3 tables, 
  #   while the last constructs 2: 5 * 3 + 2 = 17
  PE_NUM_TABLE_CONSTRUCTION: 5

  # stage 5
  # (HBM_CHANNEL_NUM * 3 / STAGE5_COMP_PE_NUM) must be integar
  # e.g., default 1 HBM channel -> 3 PQ code streams -> STAGE5_COMP_PE_NUM = 3 * HBM_CHANNEL_NUM
  # e.g., merge content of 1 HBM channel to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM
  # e.g., merge content of 2 HBM channels to 1 PQ code stream -> STAGE5_COMP_PE_NUM = HBM_CHANNEL_NUM / 2
  HBM_CHANNEL_NUM: 19 # PQ code stream num = 3 * HBM_CHANNEL_NUM
  STAGE5_COMP_PE_NUM: 57

  # stage 6
  # there could be a sorting network before the priority queue group (SORT_GROUP_ENABLE)
  #   if not, set SORT_GROUP_ENABLE to False, and SORT_GROUP_NUM to 0 or None
  # number of 16 outputs per cycle, e.g., HBM channel num = 10, comp PE num = 30, then 
  #   SORT_GROUP_NUM = 2; if HBM channel = 12, PE_num = 36, then SORT_GROUP_NUM = 3
  SORT_GROUP_ENABLE: False
  SORT_GROUP_NUM: 0 # only used when SORT_GROUP_ENABLE=True
  STAGE_6_PRIORITY_QUEUE_LEVEL: 2 # supported level num: 2 or 3
  # only fill STAGE_6_PRIORITY_QUEUE_L2_NUM, STAGE_6_STREAM_PER_L2_QUEUE_LARGER, STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  #   when STAGE_6_PRIORITY_QUEUE_LEVEL = 3, else left them blank
  # Must subject to: L1 stream num = (without sort-reduction unit) STAGE5_COMP_PE_NUM * 2 
  #                  or = (with sort reduction) 16 * 2
  # (STAGE_6_PRIORITY_QUEUE_L2_NUM - 1) * STAGE_6_STREAM_PER_L2_QUEUE_LARGER + STAGE_6_STREAM_PER_L2_QUEUE_SMALLER
  # STAGE_6_PRIORITY_QUEUE_L2_NUM: 2 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_LARGER: 6 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3
  # STAGE_6_STREAM_PER_L2_QUEUE_SMALLER: 4 # only used when when STAGE_6_PRIORITY_QUEUE_LEVEL = 3

  # Dataset config
  DB_NAME: SIFT100M
  DB_SCALE: 100M # 1M to 1000M
  FPGA_NUM: 1 # e.g., can use 8 FPGAs to serve 1000M dataset, each stores 125M vectors

  # Data directory (don't add "/" after the dir)
  #   e.g., dir=/home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks, 
  #     then the content for HBM0 is:
  #     /home/wejiang/saved_npy_data/FPGA_data_SIFT100M_OPQ16,IVF8192,PQ16_HBM_10_banks/HBM_bank_0_raw
  # DATA_DIR: "/mnt/scratch/wenqi/saved_npy_data/FPGA_data_SIFT100M_IVF4096,PQ16_23_banks"
  # GT_DIR: "/mnt/scratch/wenqi/saved_npy_data/gnd/"

  # FPGA Settings
  DEVICE: U280 # Supported devices: U280, U250, U50
  FREQ: 140
